INSERT INTO iblis.facilities(name) VALUES ('Beyond Zero Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Liza Medical clinic');
INSERT INTO iblis.facilities(name) VALUES ('Robarisia Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Border View Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Kamsaki Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Impact RDO Clinic-Nyatike');
INSERT INTO iblis.facilities(name) VALUES ('Kanga Onditi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Bondo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyamilu Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Masaria Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Doctors Worldwide Tembo Medical Centre');
INSERT INTO iblis.facilities(name) VALUES ('Kogelo Oasis Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('P&D Health Clinic Ulanda');
INSERT INTO iblis.facilities(name) VALUES ('Oasis Care Centre Andapol Clinic Awendo');
INSERT INTO iblis.facilities(name) VALUES ('Tiba Medical Center');
INSERT INTO iblis.facilities(name) VALUES ('Akidiva Kehancha Outpatient Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Kohanga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyankore Health Center');
INSERT INTO iblis.facilities(name) VALUES ('Ogongo Community Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Gosebe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Dalcoo Medical Centre');
INSERT INTO iblis.facilities(name) VALUES ('Rongo University College Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Ropment Medical Centre');
INSERT INTO iblis.facilities(name) VALUES ('Muhuru Bay VCT Centre (Nyarami)');
INSERT INTO iblis.facilities(name) VALUES ('Lwanda Konyango VCT Centre (Nyarami)');
INSERT INTO iblis.facilities(name) VALUES ('Obware Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Adoma Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Lwala Nyarago Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('LELA Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kome Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kemakoba Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ladopharma Medical Center');
INSERT INTO iblis.facilities(name) VALUES ('Metropolitan Medical Clinic - Kehancha');
INSERT INTO iblis.facilities(name) VALUES ('Ntunyigi Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Kibera Community Self Help Program - Migori');
INSERT INTO iblis.facilities(name) VALUES ('Star-Heal Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Kochola Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kuira District Disability Network Kuria - Isebania HTC Center');
INSERT INTO iblis.facilities(name) VALUES ('Hekima HTC Center');
INSERT INTO iblis.facilities(name) VALUES ('Nyasoko Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Thimjope Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Oasis Doctors Plaza Medical Centre');
INSERT INTO iblis.facilities(name) VALUES ('St Akidiva Mindira Hospital - Mabera');
INSERT INTO iblis.facilities(name) VALUES ('Imc Tekeleza Dice - Isebania');
INSERT INTO iblis.facilities(name) VALUES ('Mama Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Imc Tekeleza Dice Clinic Muhuru');
INSERT INTO iblis.facilities(name) VALUES ('Imc Tekeleza Dice Clinic Karungu');
INSERT INTO iblis.facilities(name) VALUES ('Got Kachola Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Pona VCT');
INSERT INTO iblis.facilities(name) VALUES ('Ladopharma Medical Centre');
INSERT INTO iblis.facilities(name) VALUES ('Dice Clinic Migori');
INSERT INTO iblis.facilities(name) VALUES ('Tuungane Centre Awendo');
INSERT INTO iblis.facilities(name) VALUES ('Tuungane Centre Rongo');
INSERT INTO iblis.facilities(name) VALUES ('Rapando VCT');
INSERT INTO iblis.facilities(name) VALUES ('Awendo Jiwdendi');
INSERT INTO iblis.facilities(name) VALUES ('Rosewood Nursing Home');
INSERT INTO iblis.facilities(name) VALUES ('Alpha Community Health Clinic (Migori)');
INSERT INTO iblis.facilities(name) VALUES ('Msomi Complex Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Exodus Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Bondo Nyironge Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Nyikendo Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Nyarami VCT');
INSERT INTO iblis.facilities(name) VALUES ('Migori Health Station Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Impact Rdo Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Ondong Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Mamu Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Bahati Medical Clinic Migori');
INSERT INTO iblis.facilities(name) VALUES ('Brase Clinic and Eye Centre');
INSERT INTO iblis.facilities(name) VALUES ('GK Prison Dispensary (Migori)');
INSERT INTO iblis.facilities(name) VALUES ('Ombo Bita Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ndege Oriedo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kolwal Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Piny Owacho Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Midida Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Siruti Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Angaga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ombo Kowiti Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Koloo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Motemorabu Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kituka Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyamekongoroto Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Taranganya Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Getongoroma Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kombe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Mogori-Komasimo Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Osogo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyarongi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ochuna Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kebaroti Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ulanda Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Oruba Nursing and Maternity Home');
INSERT INTO iblis.facilities(name) VALUES ('Sori Lakeside Nursing and Maternity Home');
INSERT INTO iblis.facilities(name) VALUES ('Royal Nursing Home');
INSERT INTO iblis.facilities(name) VALUES ('Suna Nursing and Maternity Home');
INSERT INTO iblis.facilities(name) VALUES ('Jevros Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Rapcom Nursing and Maternity Home');
INSERT INTO iblis.facilities(name) VALUES ('Mama Fridah Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Kehancha Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Mama Caro Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Getontira Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Huduma Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Border Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Ikerege Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Moshi Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Komomange Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Mama Maria Clinic');
INSERT INTO iblis.facilities(name) VALUES ('St Hellens Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Matoso Health Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Kopanga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kegonga Sub County Hospital');
INSERT INTO iblis.facilities(name) VALUES ('St Akidiva Memorial Hospital');
INSERT INTO iblis.facilities(name) VALUES ('St Camillus Mission Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Anjego Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Macalder Sub-District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Isibania Mission Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('St Kizito Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Bware Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Makararangwe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('God Jope Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('St Barnabas Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Giribe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyakuru Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kehancha Nursing and Maternity Home');
INSERT INTO iblis.facilities(name) VALUES ('Saro Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Marie Stopes Clinic (Migori)');
INSERT INTO iblis.facilities(name) VALUES ('St Joseph Mission Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Pastor Machage Memorial Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Dede Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Othoch Rakuom Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Victoria Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Nyaburi Clinic');
INSERT INTO iblis.facilities(name) VALUES ('St Agnes Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Awendo Sub-District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Yago Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyakurungoto Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Girigiri Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Getambwega Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyaitara Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Chinato Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Matare Mission Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ojele Memorial Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Karungu Sub-District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Rongo District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Ntimaru Sub-District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Kuria District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Muhuru Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Isibania Sub-District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Migori District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Oyani Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Bugumbe Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Mariwa Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Nyametaburo Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Othoro Sub District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Kugitimo Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Nyamaraga Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Tisinye Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Nyangoge Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ongo Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ogwedhi Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Masaba Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Uriri Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Sony Medical Centre');
INSERT INTO iblis.facilities(name) VALUES ('St Monica Rapogi Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Komotobo Mission Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Reusse Troyer Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Verna Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Kabuto Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('God Kwer Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Olasi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ngere Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyandago Koweru Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kipingi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kwoyo Kodalo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Aneko Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Arombe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Otacho Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyamanga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Komosoko Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Lwanda Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Suna Ragana Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyamaranya Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kuja Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ndiwa Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyamasare Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Agenga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Midoti Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Otati Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Riat Dispensary (Migori)');
INSERT INTO iblis.facilities(name) VALUES ('Sibuoche Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Wath Onger Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Gairoro Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyametembe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Iraha Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ongito Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Rabondo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ngodhe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Gwitembe Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Suna Rabuor Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Taragai Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Bande Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Siabai Makonge Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Lwala Community Health Center');
INSERT INTO iblis.facilities(name) VALUES ('Ngisiru Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyabokarange Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Luciel Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyabikaye Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Macalder Mission Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kadem Tb & Leprosy Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kamagambo Dispenasry');
INSERT INTO iblis.facilities(name) VALUES ('Oyani (SDA) Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ranen (SDA) Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ogada Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Osingo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Minyenya Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Migori T T C Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Muchebe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyasese Dispensary');
