INSERT INTO iblis.organisms(name) VALUES ('Escherichia coli');
INSERT INTO iblis.organisms(name) VALUES ('Klebsiella');
INSERT INTO iblis.organisms(name) VALUES ('Proteus spp');
INSERT INTO iblis.organisms(name) VALUES ('Pseudomonas aeruginosa');
INSERT INTO iblis.organisms(name) VALUES ('Staphylococcus');
INSERT INTO iblis.organisms(name) VALUES ('Enterococcus');
INSERT INTO iblis.organisms(name) VALUES ('Candida albicans');
INSERT INTO iblis.organisms(name) VALUES ('Adenovirus type 11');
INSERT INTO iblis.organisms(name) VALUES ('Enterobacter');
INSERT INTO iblis.organisms(name) VALUES ('Enterococcus faecalis');
INSERT INTO iblis.organisms(name) VALUES ('Coliforms');
INSERT INTO iblis.organisms(name) VALUES ('Shigella');
INSERT INTO iblis.organisms(name) VALUES ('Vibrio cholerae O1');
INSERT INTO iblis.organisms(name) VALUES ('Vibrio cholerae O 139');
INSERT INTO iblis.organisms(name) VALUES ('Salmonella species');
INSERT INTO iblis.organisms(name) VALUES ('Yersinia enterocolitica');
INSERT INTO iblis.organisms(name) VALUES ('Campylobacter jejuni');
INSERT INTO iblis.organisms(name) VALUES ('Yersinia pestis');
INSERT INTO iblis.organisms(name) VALUES ('Streptococci pyogenes');
INSERT INTO iblis.organisms(name) VALUES ('Klebsiella spp');
INSERT INTO iblis.organisms(name) VALUES ('Bacillus anthracis');
INSERT INTO iblis.organisms(name) VALUES ('Neisseria meningitidis');
INSERT INTO iblis.organisms(name) VALUES ('Neisseria gonorrhoeae');
INSERT INTO iblis.organisms(name) VALUES ('Streptococci pneumoniae');
INSERT INTO iblis.organisms(name) VALUES ('Cryptococcus neoformans');
INSERT INTO iblis.organisms(name) VALUES ('Cryptococcus meningitis');
INSERT INTO iblis.organisms(name) VALUES ('Gardinerella vaginalis');
INSERT INTO iblis.organisms(name) VALUES ('Trichomonas vaginalis');
INSERT INTO iblis.organisms(name) VALUES ('Vibro cholerae O1');
INSERT INTO iblis.organisms(name) VALUES ('Vibro cholerae O 139');
INSERT INTO iblis.organisms(name) VALUES ('Mycobacterium tuberculosis');
INSERT INTO iblis.organisms(name) VALUES ('Streptococcus Pneumoniae');
INSERT INTO iblis.organisms(name) VALUES ('Pseudomonas spp');
INSERT INTO iblis.organisms(name) VALUES ('Staphylococcus spp');
INSERT INTO iblis.organisms(name) VALUES ('Enterococcus spp');
INSERT INTO iblis.organisms(name) VALUES ('Bacillus spp');
INSERT INTO iblis.organisms(name) VALUES ('Group D Streptococcus');
INSERT INTO iblis.organisms(name) VALUES ('Klebsiella pneumoniae');
INSERT INTO iblis.organisms(name) VALUES ('Group A beta haemolytic streptococcus');
INSERT INTO iblis.organisms(name) VALUES ('Corynebacterium Diptheriae');
INSERT INTO iblis.organisms(name) VALUES ('Neisseria meningitides');
INSERT INTO iblis.organisms(name) VALUES ('Streptococcus Group A');
INSERT INTO iblis.organisms(name) VALUES ('Enterococci');
INSERT INTO iblis.organisms(name) VALUES ('Staphylococcus aureus');
INSERT INTO iblis.organisms(name) VALUES ('Bacteroids');
INSERT INTO iblis.organisms(name) VALUES ('Clostridium');
INSERT INTO iblis.organisms(name) VALUES ('Staphylococci aureus');
INSERT INTO iblis.organisms(name) VALUES ('Pseudomonas');
INSERT INTO iblis.organisms(name) VALUES ('Haemophillus spp');
INSERT INTO iblis.organisms(name) VALUES ('Haemophilus influenzae');
INSERT INTO iblis.organisms(name) VALUES ('Streptococcus pyogenes');
