INSERT INTO iblis.specimen_types(name) VALUES ('Whole blood');
INSERT INTO iblis.specimen_types(name) VALUES ('Blood smear');
INSERT INTO iblis.specimen_types(name) VALUES ('Urine');
INSERT INTO iblis.specimen_types(name) VALUES ('Stool');
INSERT INTO iblis.specimen_types(name) VALUES ('Pus Swab');
INSERT INTO iblis.specimen_types(name) VALUES ('Throat Swab');
INSERT INTO iblis.specimen_types(name) VALUES ('High vaginal swab');
INSERT INTO iblis.specimen_types(name) VALUES ('Urethral swab');
INSERT INTO iblis.specimen_types(name) VALUES ('Ascetic fluid');
INSERT INTO iblis.specimen_types(name) VALUES ('Pleural fluid');
INSERT INTO iblis.specimen_types(name) VALUES ('CSF');
INSERT INTO iblis.specimen_types(name) VALUES ('Sputum');
INSERT INTO iblis.specimen_types(name) VALUES ('Serum');
INSERT INTO iblis.specimen_types(name) VALUES ('Plasma');
INSERT INTO iblis.specimen_types(name) VALUES ('Dried blood spot (DBS)');
INSERT INTO iblis.specimen_types(name) VALUES ('Rectal swab');
INSERT INTO iblis.specimen_types(name) VALUES ('Water Samples');
INSERT INTO iblis.specimen_types(name) VALUES ('Food samples');
INSERT INTO iblis.specimen_types(name) VALUES ('Bone marrow');
INSERT INTO iblis.specimen_types(name) VALUES ('Skin scrapings');
INSERT INTO iblis.specimen_types(name) VALUES ('Nails');
INSERT INTO iblis.specimen_types(name) VALUES ('Tissue smears');
INSERT INTO iblis.specimen_types(name) VALUES ('Smear');
INSERT INTO iblis.specimen_types(name) VALUES ('Tissue');
