INSERT INTO iblis.facilities(name) VALUES ('Uhembo Community Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Linda Jamii Clinic - Aram Mkt');
INSERT INTO iblis.facilities(name) VALUES ('Omboye Ubuntu Afya Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Ruma Ubuntu Afya Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Lwako Ubuntu Afya Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Pamoja Medical Centre');
INSERT INTO iblis.facilities(name) VALUES ('Home Ground Nursing Home');
INSERT INTO iblis.facilities(name) VALUES ('CFW Clinic Ugunja');
INSERT INTO iblis.facilities(name) VALUES ('Siaya County Referral Beyond Zero Moble Clinic Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ubuntu Afya Ninalakeside Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Tumaini Wellness Centre');
INSERT INTO iblis.facilities(name) VALUES ('Relief Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Nyandwela Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Lwanda kobita');
INSERT INTO iblis.facilities(name) VALUES ('Matungu Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Buyemi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Vikunga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyayiera Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('St Mathews Kandaria Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Maliera Mission Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Harmony Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Gogo Disp');
INSERT INTO iblis.facilities(name) VALUES ('Mama Anns Odede Community Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Nyandusi');
INSERT INTO iblis.facilities(name) VALUES ('Jalsonga Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Chianda Dispensary (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Tumaini DiSC -  Asembo Bay');
INSERT INTO iblis.facilities(name) VALUES ('Hessed Clinic Masiro');
INSERT INTO iblis.facilities(name) VALUES ('Siala Kaduol');
INSERT INTO iblis.facilities(name) VALUES ('Ruma Youth Friendly VCT (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Barding Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Got Osimbo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ligala Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('GOK Prison Siaya');
INSERT INTO iblis.facilities(name) VALUES ('Riyadh Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Tuungane');
INSERT INTO iblis.facilities(name) VALUES ('Bondo University Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Bondo Town VCT');
INSERT INTO iblis.facilities(name) VALUES ('Our Lady of Perpetual Sisters VCT (Bondo)');
INSERT INTO iblis.facilities(name) VALUES ('Kopiata Beach Dispensary (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Asembo Bay Health Clinic (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Junction Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Siwadhe Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Nyadhi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Karuoth Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Uhembo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kabura Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Umer Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Matibabu Ukwala Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Matibabu Nzoia Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Kambare Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Lidha Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Mur Malanga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Future Life Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Randago Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Masogo Dispensary (Gem)');
INSERT INTO iblis.facilities(name) VALUES ('Gongo Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Oding Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Lihanda Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Lieta Health Centre (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Wagoro Dispensary (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Rambugu Dispensary (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Uradi Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Kopolo Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Almacy Medical  Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Apex Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Nyagoko Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('St Mary\'s Yala Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Asayi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Segere Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Simenya Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Tingare Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Urenga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Sifuyo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Bar-Sauri Dispensry');
INSERT INTO iblis.facilities(name) VALUES ('Umala Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Sirembe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Rera Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Misori Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Benga Bi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Bar Aluru Dispensary (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Radier Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyambare Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Aro (SDA) Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyamonye Mission Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyaguda Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kapiyo Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ndori Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ndeda Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ong\'ielo Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Manyuanda St Teresas CFW Clinic (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('St Paul Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Boro Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Owens Nursing Home');
INSERT INTO iblis.facilities(name) VALUES ('Bondo Medical Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Jamii Clinical Services Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Sega Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Inuka Hospital & Maternity Home');
INSERT INTO iblis.facilities(name) VALUES ('Sagam Community Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Bama Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Ambira Sub-District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Sumba Community Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('St Joseph\'s Obaga Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Anyuongi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Rageng\'ni Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ouya Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Gobei  Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Bar Ndege Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Wagai Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kagwa Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Usenge Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kunya Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ukwala Sub County Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Mahaya Health Centre (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Bondo District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Siaya District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Madiany Sub County  Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Got Agulu Sub-District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Yala Sub-District Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Uhuyi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Manyuanda Health Centre (Rarieda)');
INSERT INTO iblis.facilities(name) VALUES ('Abidha Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ligega Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ramula Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ndere Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Nyawara Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Matangwe Community Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Akala Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Dienya Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Malanga Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Marenyo Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ting\'wangi Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Rwambwa Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Kadenge Ratuoro Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Hawinga Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Sigomere Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Pap Kodero Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Aluor Mission Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Ng\'iya Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Sega Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Rangala Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('St Elizabeth Lwak Mission Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Nyang\'oma Mission Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Usigu Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Masala Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyenye Misori Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Mawere Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Mageta Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Got Matar Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ogam Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kambajo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Othach Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Saradidi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Uyawi Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Naya Health Centre');
INSERT INTO iblis.facilities(name) VALUES ('Serawongo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Oyamo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Mabinju Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Midhine Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ogero Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Ulungo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Bar Olengo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Uzima Clinic');
INSERT INTO iblis.facilities(name) VALUES ('Mulaha Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Uriri Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kaluo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Nyathengo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Kogelo Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Rabar Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Masumbi Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Mwer Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Sega Cottage Hospital');
INSERT INTO iblis.facilities(name) VALUES ('Nyangu Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Uluthe Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Jera Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Bar Agulu Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Bar Achuth Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Sikalame Dispensary');
INSERT INTO iblis.facilities(name) VALUES ('Rambula Dispensary');
