<?php

class MeasureSeed extends KBLISSeeder
{
	public static function get()
	{
		return array(
			array('id' => '197', 'measure_type_id' => '2', 'name' => 'Grams stain', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '200', 'measure_type_id' => '2', 'name' => 'SERUM AMYLASE', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '201', 'measure_type_id' => '2', 'name' => 'calcium', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '203', 'measure_type_id' => '1', 'name' => 'URIC ACID', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '210', 'measure_type_id' => '4', 'name' => 'CSF for biochemistry', 'measure_range' => '', 'unit' => ''),
			array('id' => '211', 'measure_type_id' => '4', 'name' => 'PSA', 'measure_range' => '', 'unit' => ''),
			array('id' => '212', 'measure_type_id' => '1', 'name' => 'Total', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '214', 'measure_type_id' => '1', 'name' => 'Alkaline Phosphate', 'measure_range' => '', 'unit' => 'u/l'),
			array('id' => '216', 'measure_type_id' => '2', 'name' => 'SGOT', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '218', 'measure_type_id' => '1', 'name' => 'Direct ', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '219', 'measure_type_id' => '1', 'name' => 'Total Proteins ', 'measure_range' => '', 'unit' => ''),
			array('id' => '221', 'measure_type_id' => '4', 'name' => 'LFTS', 'measure_range' => '', 'unit' => ''),
			array('id' => '222', 'measure_type_id' => '1', 'name' => 'Chloride', 'measure_range' => '', 'unit' => 'mmol/l'),
			array('id' => '223', 'measure_type_id' => '1', 'name' => 'Potassium', 'measure_range' => '', 'unit' => 'mmol/l'),
			array('id' => '224', 'measure_type_id' => '1', 'name' => 'Sodium', 'measure_range' => '', 'unit' => 'mmol/l'),
			array('id' => '225', 'measure_type_id' => '4', 'name' => 'Electrolytes', 'measure_range' => '', 'unit' => ''),
			array('id' => '226', 'measure_type_id' => '1', 'name' => 'Creatinine ', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '227', 'measure_type_id' => '1', 'name' => 'Urea', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '228', 'measure_type_id' => '4', 'name' => 'RFTS', 'measure_range' => '', 'unit' => ''),
			array('id' => '229', 'measure_type_id' => '4', 'name' => 'TFT', 'measure_range' => '', 'unit' => ''),
			array('id' => '230', 'measure_type_id' => '4', 'name' => 'GXM', 'measure_range' => '', 'unit' => ''),
			array('id' => '231', 'measure_type_id' => '2', 'name' => 'Indirect COOMBS test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '232', 'measure_type_id' => '2', 'name' => 'Direct COOMBS test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '233', 'measure_type_id' => '2', 'name' => 'Du test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '234', 'measure_type_id' => '2', 'name' => 'Blood Grouping', 'measure_range' => 'O-/O+/A-/A+/B-/B+/AB-/AB+', 'unit' => ''),
			array('id' => '235', 'measure_type_id' => '2', 'name' => 'Cross Match', 'measure_range' => 'Pending/Done', 'unit' => ''),
			array('id' => '236', 'measure_type_id' => '4', 'name' => 'Epithelial cells', 'measure_range' => '', 'unit' => ''),
			array('id' => '238', 'measure_type_id' => '4', 'name' => 'ph', 'measure_range' => '', 'unit' => ''),
			array('id' => '239', 'measure_type_id' => '2', 'name' => 'Blood sugar', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '240', 'measure_type_id' => '4', 'name' => 'Spermatozoa', 'measure_range' => '', 'unit' => ''),
			array('id' => '241', 'measure_type_id' => '4', 'name' => 'Bacteria', 'measure_range' => '', 'unit' => ''),
			array('id' => '242', 'measure_type_id' => '4', 'name' => 'Red blood cells', 'measure_range' => '', 'unit' => ''),
			array('id' => '243', 'measure_type_id' => '4', 'name' => 'Yeast cells', 'measure_range' => '', 'unit' => ''),
			array('id' => '244', 'measure_type_id' => '4', 'name' => 'T. vaginalis', 'measure_range' => '', 'unit' => ''),
			array('id' => '245', 'measure_type_id' => '4', 'name' => 'S. haematobium', 'measure_range' => '', 'unit' => ''),
			array('id' => '246', 'measure_type_id' => '4', 'name' => 'Pus cells', 'measure_range' => '', 'unit' => ''),
			array('id' => '247', 'measure_type_id' => '2', 'name' => 'Urine microscopy', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '248', 'measure_type_id' => '4', 'name' => 'HCG', 'measure_range' => '', 'unit' => ''),
			array('id' => '249', 'measure_type_id' => '4', 'name' => 'Urobilinogen Phenlpyruvic acid', 'measure_range' => '', 'unit' => ''),
			array('id' => '251', 'measure_type_id' => '4', 'name' => 'Blood', 'measure_range' => '', 'unit' => ''),
			array('id' => '252', 'measure_type_id' => '4', 'name' => 'Proteins', 'measure_range' => '', 'unit' => ''),
			array('id' => '253', 'measure_type_id' => '4', 'name' => 'Ketones', 'measure_range' => '', 'unit' => ''),
			array('id' => '256', 'measure_type_id' => '1', 'name' => 'Baso#', 'measure_range' => '', 'unit' => '%'),
			array('id' => '257', 'measure_type_id' => '1', 'name' => 'Eos#', 'measure_range' => '', 'unit' => ''),
			array('id' => '258', 'measure_type_id' => '1', 'name' => 'Mon#', 'measure_range' => '', 'unit' => ''),
			array('id' => '259', 'measure_type_id' => '1', 'name' => 'Lym#', 'measure_range' => '', 'unit' => ''),
			array('id' => '260', 'measure_type_id' => '1', 'name' => 'Neu#', 'measure_range' => '', 'unit' => ''),
			array('id' => '261', 'measure_type_id' => '1', 'name' => 'WBC', 'measure_range' => '', 'unit' => 'x10Â³/ÂµL'),
			array('id' => '262', 'measure_type_id' => '1', 'name' => 'RBC', 'measure_range' => '', 'unit' => 'x10â¶/ÂµL'),
			array('id' => '263', 'measure_type_id' => '1', 'name' => 'HB', 'measure_range' => '', 'unit' => 'g/dL'),
			array('id' => '264', 'measure_type_id' => '1', 'name' => 'HCT', 'measure_range' => '', 'unit' => '%'),
			array('id' => '265', 'measure_type_id' => '1', 'name' => 'MCV', 'measure_range' => '', 'unit' => 'fL'),
			array('id' => '266', 'measure_type_id' => '1', 'name' => 'MCH', 'measure_range' => '', 'unit' => 'pg'),
			array('id' => '267', 'measure_type_id' => '1', 'name' => 'MCHC', 'measure_range' => '', 'unit' => 'g/dL'),
			array('id' => '268', 'measure_type_id' => '1', 'name' => 'RDW', 'measure_range' => '', 'unit' => '%'),
			array('id' => '269', 'measure_type_id' => '1', 'name' => 'PLATELET COUNT', 'measure_range' => '', 'unit' => 'x10Â³/ÂµL'),
			array('id' => '270', 'measure_type_id' => '1', 'name' => 'PCT', 'measure_range' => '', 'unit' => '%'),
			array('id' => '272', 'measure_type_id' => '1', 'name' => 'PDW', 'measure_range' => '', 'unit' => '%'),
			array('id' => '273', 'measure_type_id' => '4', 'name' => 'Full Haemogram', 'measure_range' => '', 'unit' => ''),
			array('id' => '274', 'measure_type_id' => '4', 'name' => 'Bleeding time test', 'measure_range' => '', 'unit' => ''),
			array('id' => '275', 'measure_type_id' => '4', 'name' => 'Clotting time test', 'measure_range' => '', 'unit' => ''),
			array('id' => '276', 'measure_type_id' => '4', 'name' => 'PTI/INR', 'measure_range' => '', 'unit' => ''),
			array('id' => '277', 'measure_type_id' => '2', 'name' => 'Sickling test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '278', 'measure_type_id' => '2', 'name' => 'ESR', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '282', 'measure_type_id' => '4', 'name' => 'Gramstain', 'measure_range' => '', 'unit' => ''),
			array('id' => '284', 'measure_type_id' => '4', 'name' => 'microscopy', 'measure_range' => '', 'unit' => ''),
			array('id' => '298', 'measure_type_id' => '4', 'name' => 'Throat swab for culture', 'measure_range' => '', 'unit' => ''),
			array('id' => '302', 'measure_type_id' => '4', 'name' => 'microscopic examination', 'measure_range' => '', 'unit' => ''),
			array('id' => '303', 'measure_type_id' => '4', 'name' => 'sperm count', 'measure_range' => '', 'unit' => ''),
			array('id' => '304', 'measure_type_id' => '2', 'name' => 'motility', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '305', 'measure_type_id' => '2', 'name' => 'viscosity', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '306', 'measure_type_id' => '4', 'name' => 'volume', 'measure_range' => '', 'unit' => ''),
			array('id' => '322', 'measure_type_id' => '4', 'name' => 'wet prep', 'measure_range' => '', 'unit' => ''),
			array('id' => '335', 'measure_type_id' => '2', 'name' => 'Indian ink', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '338', 'measure_type_id' => '1', 'name' => 'cell count', 'measure_range' => 'Number (count/ml)', 'unit' => ''),
			array('id' => '343', 'measure_type_id' => '4', 'name' => 'culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '345', 'measure_type_id' => '4', 'name' => 'CSF for microbiology', 'measure_range' => '', 'unit' => ''),
			array('id' => '346', 'measure_type_id' => '4', 'name' => 'Pus swab for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '347', 'measure_type_id' => '2', 'name' => 'KOH for fungi', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '348', 'measure_type_id' => '4', 'name' => 'semen analysis', 'measure_range' => '', 'unit' => ''),
			array('id' => '350', 'measure_type_id' => '4', 'name' => 'Aspirate for microscopy ', 'measure_range' => '', 'unit' => ''),
			array('id' => '351', 'measure_type_id' => '4', 'name' => 'HVS for microscopy ', 'measure_range' => '', 'unit' => ''),
			array('id' => '352', 'measure_type_id' => '4', 'name' => 'Synovial fluid for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '353', 'measure_type_id' => '4', 'name' => 'Synovial fluid for microscopy', 'measure_range' => '', 'unit' => ''),
			array('id' => '354', 'measure_type_id' => '4', 'name' => 'Pleural tap for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '355', 'measure_type_id' => '4', 'name' => 'Pleural tap for microscopy', 'measure_range' => '', 'unit' => ''),
			array('id' => '358', 'measure_type_id' => '4', 'name' => 'Urine Culture and Sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '359', 'measure_type_id' => '4', 'name' => 'Water Analysis', 'measure_range' => '', 'unit' => ''),
			array('id' => '361', 'measure_type_id' => '2', 'name' => 'Gram stain', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '362', 'measure_type_id' => '2', 'name' => 'Sub culture ', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '363', 'measure_type_id' => '4', 'name' => 'Blood Culture & sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '364', 'measure_type_id' => '4', 'name' => 'HVS for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '365', 'measure_type_id' => '2', 'name' => 'Sputum', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '366', 'measure_type_id' => '4', 'name' => 'Stool for C/S', 'measure_range' => '', 'unit' => ''),
			array('id' => '367', 'measure_type_id' => '4', 'name' => 'CSF', 'measure_range' => '', 'unit' => ''),
			array('id' => '368', 'measure_type_id' => '2', 'name' => 'salmonella antigen test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '369', 'measure_type_id' => '2', 'name' => 'OCCULT BLOOD', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '370', 'measure_type_id' => '4', 'name' => 'Stool for O/C', 'measure_range' => '', 'unit' => ''),
			array('id' => '371', 'measure_type_id' => '2', 'name' => 'BS for mps', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '372', 'measure_type_id' => '2', 'name' => 'Borrelia', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '373', 'measure_type_id' => '4', 'name' => 'PBF', 'measure_range' => '', 'unit' => ''),
			array('id' => '374', 'measure_type_id' => '2', 'name' => 'HEPATITIS C', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '375', 'measure_type_id' => '2', 'name' => 'HEPATITIS B', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '376', 'measure_type_id' => '2', 'name' => 'Asot Titration', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '377', 'measure_type_id' => '1', 'name' => 'Widal Titration', 'measure_range' => 'Number (count/ml)', 'unit' => ''),
			array('id' => '378', 'measure_type_id' => '2', 'name' => 'VDRL', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '379', 'measure_type_id' => '2', 'name' => 'Asot', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '380', 'measure_type_id' => '2', 'name' => 'Pregnancy test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '381', 'measure_type_id' => '2', 'name' => 'RF', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '382', 'measure_type_id' => '2', 'name' => 'Brucella', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '383', 'measure_type_id' => '2', 'name' => 'Widal', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '384', 'measure_type_id' => '2', 'name' => 'H pylori', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '385', 'measure_type_id' => '2', 'name' => 'CD4', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '393', 'measure_type_id' => '1', 'name' => 'HGB', 'measure_range' => '', 'unit' => 'g/dl'),
			array('id' => '403', 'measure_type_id' => '4', 'name' => 'Glucose', 'measure_range' => '', 'unit' => ''),
			array('id' => '404', 'measure_type_id' => '4', 'name' => 'Protein', 'measure_range' => '', 'unit' => ''),
			array('id' => '405', 'measure_type_id' => '4', 'name' => 'Culture', 'measure_range' => '', 'unit' => ''),
			array('id' => '406', 'measure_type_id' => '4', 'name' => 'Sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '407', 'measure_type_id' => '4', 'name' => 'ZN stain', 'measure_range' => '', 'unit' => ''),
			array('id' => '408', 'measure_type_id' => '1', 'name' => 'ALAT', 'measure_range' => '', 'unit' => 'u/l'),
			array('id' => '409', 'measure_type_id' => '1', 'name' => 'Albumin', 'measure_range' => '', 'unit' => 'g/dl'),
			array('id' => '410', 'measure_type_id' => '4', 'name' => 'sd', 'measure_range' => '', 'unit' => ''),
			array('id' => '411', 'measure_type_id' => '4', 'name' => 'Aspirate for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '412', 'measure_type_id' => '4', 'name' => 'Bilirubin', 'measure_range' => '', 'unit' => ''),
			array('id' => '413', 'measure_type_id' => '4', 'name' => 'Urinalysis', 'measure_range' => '', 'unit' => ''),
			array('id' => '414', 'measure_type_id' => '2', 'name' => 'ASAT', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '415', 'measure_type_id' => '1', 'name' => 'ASAT', 'measure_range' => '', 'unit' => 'u/l')

		);
	}
}
