<?php
class Seed extends KBLISSeeder
{
	public static function getMeasureType()
	{
		return array(
            array("id" => "1", "name" => "Numeric Range"),
            array("id" => "2", "name" => "Alphanumeric Values"),
            array("id" => "3", "name" => "Autocomplete"),
            array("id" => "4", "name" => "Free Text")
		);
	}

	public static function getRejectionReason()
	{
		return array( 
          array("reason" => "Poorly labelled"),
          array("reason" => "Over saturation"),
          array("reason" => "Insufficient Sample"),
          array("reason" => "Scattered"),
          array("reason" => "Clotted Blood"),
          array("reason" => "Two layered spots"),
          array("reason" => "Serum rings"),
          array("reason" => "Scratched"),
          array("reason" => "Haemolysis"),
          array("reason" => "Spots that cannot elute"),
          array("reason" => "Leaking"),
          array("reason" => "Broken Sample Container"),
          array("reason" => "Mismatched sample and form labelling"),
          array("reason" => "Missing Labels on container and tracking form"),
          array("reason" => "Empty Container"),
          array("reason" => "Samples without tracking forms"),
          array("reason" => "Poor transport"),
          array("reason" => "Lipaemic"),
          array("reason" => "Wrong container/Anticoagulant"),
          array("reason" => "Request form without samples"),
          array("reason" => "Missing collection date on specimen / request form."),
          array("reason" => "Name and signature of requester missing"),
          array("reason" => "Mismatched information on request form and specimen container."),
          array("reason" => "Request form contaminated with specimen"),
          array("reason" => "Duplicate specimen received"),
          array("reason" => "Delay between specimen collection and arrival in the laboratory"),
          array("reason" => "Inappropriate specimen packing"),
          array("reason" => "Inappropriate specimen for the test"),
          array("reason" => "Inappropriate test for the clinical condition"),
          array("reason" => "No Label"),
          array("reason" => "Leaking"),
          array("reason" => "No Sample in the Container"),
          array("reason" => "No Request Form"),
          array("reason" => "Missing Information Required")
		);
	}

	public static function getSpecimenStatus()
	{
		return array(
          array("id" => "1", "name" => "specimen-not-collected"),
          array("id" => "2", "name" => "specimen-accepted"),
          array("id" => "3", "name" => "specimen-rejected")
		);
	}

	public static function getSpecimenType()
	{
		return array(
			array('id' => '6', 'name' => 'Whole Blood'),
			array('id' => '7', 'name' => 'Serum'),
			array('id' => '8', 'name' => 'Dried Blood Spot'),
			array('id' => '9', 'name' => 'Sputum'),
			array('id' => '10', 'name' => 'CSF'),
			array('id' => '11', 'name' => 'Urine'),
			array('id' => '12', 'name' => 'Stool'),
			array('id' => '13', 'name' => 'Aspirate'),
			array('id' => '14', 'name' => 'Nasal Swab'),
			array('id' => '15', 'name' => 'Semen'),
			array('id' => '16', 'name' => 'Rectal Swab'),
			array('id' => '17', 'name' => 'Throat Swab'),
			array('id' => '18', 'name' => 'Plasma EDTA'),
			array('id' => '21', 'name' => 'Vaginal Smear'),
			array('id' => '22', 'name' => 'Skin'),
			array('id' => '23', 'name' => 'Plasma'),
			array('id' => '24', 'name' => 'Urethral Smear'),
			array('id' => '25', 'name' => 'High Vaginal Swab'),
			array('id' => '26', 'name' => 'Ascitic Tap'),
			array('id' => '27', 'name' => 'Synovial Fluid'),
			array('id' => '28', 'name' => 'Pleural Tap'),
			array('id' => '29', 'name' => 'Water'),
			array('id' => '30', 'name' => 'Pus Swab')
		);
	}

	public static function getTestCategory()
	{
		return array(
			array('id' => '1', 'name' => 'SEROLOGY'),
			array('id' => '2', 'name' => 'HAEMATOLOGY'),
			array('id' => '3', 'name' => 'MCH'),
			array('id' => '4', 'name' => 'VIROLOGY'),
			array('id' => '5', 'name' => 'HISTOLOGY AND CYTOLOGY'),
			array('id' => '6', 'name' => 'BIOCHEMISTRY'),
			array('id' => '7', 'name' => 'MICROBIOLOGY'),
			array('id' => '8', 'name' => 'OTHER'),
			array('id' => '9', 'name' => 'CLINICAL CHEMISTRY'),
			array('id' => '10', 'name' => 'BACTERIOLOGY'),
			array('id' => '12', 'name' => 'PARASITOLOGY'),
			array('id' => '13', 'name' => 'BLOOD TRANSFUSION'),
			array('id' => '14', 'name' => 'Test Section')
		);
	}

	public static function getTestPhase()
	{
		return array(
          array("id" => "1", "name" => "Pre-Analytical"),
          array("id" => "2", "name" => "Analytical"),
          array("id" => "3", "name" => "Post-Analytical")
		);
	}

	public static function getTestStatus()
	{
		return array(
          array("id" => "1","name" => "not-received","test_phase_id" => "1"),//Pre-Analytical
          array("id" => "2","name" => "pending","test_phase_id" => "1"),//Pre-Analytical
          array("id" => "3","name" => "started","test_phase_id" => "2"),//Analytical
          array("id" => "4","name" => "completed","test_phase_id" => "3"),//Post-Analytical
          array("id" => "5","name" => "verified","test_phase_id" => "3")//Post-Analytical
		);
	}


	public static function getTestTypeMeasure()
	{
		return array(
			array('id' => '1', 'test_type_id' => '117', 'measure_id' => '197'),
			array('id' => '2', 'test_type_id' => '120', 'measure_id' => '200'),
			array('id' => '3', 'test_type_id' => '123', 'measure_id' => '203'),
			array('id' => '4', 'test_type_id' => '124', 'measure_id' => '201'),
			array('id' => '5', 'test_type_id' => '127', 'measure_id' => '403'),
			array('id' => '6', 'test_type_id' => '127', 'measure_id' => '404'),
			array('id' => '7', 'test_type_id' => '131', 'measure_id' => '211'),
			array('id' => '8', 'test_type_id' => '132', 'measure_id' => '212'),
			array('id' => '9', 'test_type_id' => '134', 'measure_id' => '214'),
			array('id' => '10', 'test_type_id' => '135', 'measure_id' => '415'),
			array('id' => '11', 'test_type_id' => '136', 'measure_id' => '216'),
			array('id' => '12', 'test_type_id' => '137', 'measure_id' => '408'),
			array('id' => '13', 'test_type_id' => '138', 'measure_id' => '218'),
			array('id' => '14', 'test_type_id' => '139', 'measure_id' => '219'),
			array('id' => '15', 'test_type_id' => '141', 'measure_id' => '212'),
			array('id' => '16', 'test_type_id' => '141', 'measure_id' => '214'),
			array('id' => '17', 'test_type_id' => '141', 'measure_id' => '216'),
			array('id' => '18', 'test_type_id' => '141', 'measure_id' => '218'),
			array('id' => '19', 'test_type_id' => '141', 'measure_id' => '219'),
			array('id' => '20', 'test_type_id' => '141', 'measure_id' => '408'),
			array('id' => '21', 'test_type_id' => '141', 'measure_id' => '409'),
			array('id' => '22', 'test_type_id' => '141', 'measure_id' => '412'),
			array('id' => '23', 'test_type_id' => '141', 'measure_id' => '414'),
			array('id' => '24', 'test_type_id' => '142', 'measure_id' => '222'),
			array('id' => '25', 'test_type_id' => '143', 'measure_id' => '223'),
			array('id' => '26', 'test_type_id' => '144', 'measure_id' => '224'),
			array('id' => '27', 'test_type_id' => '145', 'measure_id' => '222'),
			array('id' => '28', 'test_type_id' => '145', 'measure_id' => '223'),
			array('id' => '29', 'test_type_id' => '145', 'measure_id' => '224'),
			array('id' => '30', 'test_type_id' => '146', 'measure_id' => '226'),
			array('id' => '31', 'test_type_id' => '147', 'measure_id' => '227'),
			array('id' => '32', 'test_type_id' => '148', 'measure_id' => '222'),
			array('id' => '33', 'test_type_id' => '148', 'measure_id' => '223'),
			array('id' => '34', 'test_type_id' => '148', 'measure_id' => '224'),
			array('id' => '35', 'test_type_id' => '148', 'measure_id' => '225'),
			array('id' => '36', 'test_type_id' => '148', 'measure_id' => '226'),
			array('id' => '37', 'test_type_id' => '148', 'measure_id' => '227'),
			array('id' => '38', 'test_type_id' => '149', 'measure_id' => '229'),
			array('id' => '39', 'test_type_id' => '150', 'measure_id' => '234'),
			array('id' => '40', 'test_type_id' => '150', 'measure_id' => '235'),
			array('id' => '41', 'test_type_id' => '151', 'measure_id' => '231'),
			array('id' => '42', 'test_type_id' => '152', 'measure_id' => '232'),
			array('id' => '43', 'test_type_id' => '153', 'measure_id' => '233'),
			array('id' => '44', 'test_type_id' => '154', 'measure_id' => '234'),
			array('id' => '45', 'test_type_id' => '155', 'measure_id' => '235'),
			array('id' => '46', 'test_type_id' => '156', 'measure_id' => '236'),
			array('id' => '47', 'test_type_id' => '157', 'measure_id' => '413'),
			array('id' => '48', 'test_type_id' => '158', 'measure_id' => '238'),
			array('id' => '49', 'test_type_id' => '159', 'measure_id' => '239'),
			array('id' => '50', 'test_type_id' => '160', 'measure_id' => '240'),
			array('id' => '51', 'test_type_id' => '161', 'measure_id' => '241'),
			array('id' => '52', 'test_type_id' => '162', 'measure_id' => '242'),
			array('id' => '53', 'test_type_id' => '163', 'measure_id' => '243'),
			array('id' => '54', 'test_type_id' => '164', 'measure_id' => '244'),
			array('id' => '55', 'test_type_id' => '165', 'measure_id' => '245'),
			array('id' => '56', 'test_type_id' => '166', 'measure_id' => '246'),
			array('id' => '57', 'test_type_id' => '167', 'measure_id' => '240'),
			array('id' => '58', 'test_type_id' => '167', 'measure_id' => '241'),
			array('id' => '59', 'test_type_id' => '167', 'measure_id' => '242'),
			array('id' => '60', 'test_type_id' => '167', 'measure_id' => '243'),
			array('id' => '61', 'test_type_id' => '167', 'measure_id' => '244'),
			array('id' => '62', 'test_type_id' => '167', 'measure_id' => '245'),
			array('id' => '63', 'test_type_id' => '167', 'measure_id' => '246'),
			array('id' => '64', 'test_type_id' => '168', 'measure_id' => '248'),
			array('id' => '65', 'test_type_id' => '169', 'measure_id' => '249'),
			array('id' => '66', 'test_type_id' => '170', 'measure_id' => '212'),
			array('id' => '67', 'test_type_id' => '170', 'measure_id' => '218'),
			array('id' => '68', 'test_type_id' => '171', 'measure_id' => '251'),
			array('id' => '69', 'test_type_id' => '172', 'measure_id' => '252'),
			array('id' => '70', 'test_type_id' => '173', 'measure_id' => '253'),
			array('id' => '71', 'test_type_id' => '175', 'measure_id' => '248'),
			array('id' => '72', 'test_type_id' => '175', 'measure_id' => '249'),
			array('id' => '73', 'test_type_id' => '175', 'measure_id' => '251'),
			array('id' => '74', 'test_type_id' => '175', 'measure_id' => '252'),
			array('id' => '75', 'test_type_id' => '175', 'measure_id' => '253'),
			array('id' => '76', 'test_type_id' => '175', 'measure_id' => '403'),
			array('id' => '77', 'test_type_id' => '175', 'measure_id' => '412'),
			array('id' => '78', 'test_type_id' => '176', 'measure_id' => '256'),
			array('id' => '79', 'test_type_id' => '176', 'measure_id' => '257'),
			array('id' => '80', 'test_type_id' => '176', 'measure_id' => '258'),
			array('id' => '81', 'test_type_id' => '176', 'measure_id' => '259'),
			array('id' => '82', 'test_type_id' => '176', 'measure_id' => '260'),
			array('id' => '83', 'test_type_id' => '176', 'measure_id' => '261'),
			array('id' => '84', 'test_type_id' => '176', 'measure_id' => '262'),
			array('id' => '85', 'test_type_id' => '176', 'measure_id' => '263'),
			array('id' => '86', 'test_type_id' => '176', 'measure_id' => '264'),
			array('id' => '87', 'test_type_id' => '176', 'measure_id' => '265'),
			array('id' => '88', 'test_type_id' => '176', 'measure_id' => '266'),
			array('id' => '89', 'test_type_id' => '176', 'measure_id' => '267'),
			array('id' => '90', 'test_type_id' => '176', 'measure_id' => '268'),
			array('id' => '91', 'test_type_id' => '176', 'measure_id' => '269'),
			array('id' => '92', 'test_type_id' => '176', 'measure_id' => '270'),
			array('id' => '93', 'test_type_id' => '176', 'measure_id' => '272'),
			array('id' => '94', 'test_type_id' => '181', 'measure_id' => '256'),
			array('id' => '95', 'test_type_id' => '181', 'measure_id' => '257'),
			array('id' => '96', 'test_type_id' => '181', 'measure_id' => '258'),
			array('id' => '97', 'test_type_id' => '181', 'measure_id' => '259'),
			array('id' => '98', 'test_type_id' => '181', 'measure_id' => '260'),
			array('id' => '99', 'test_type_id' => '181', 'measure_id' => '261'),
			array('id' => '100', 'test_type_id' => '182', 'measure_id' => '262'),
			array('id' => '101', 'test_type_id' => '183', 'measure_id' => '263'),
			array('id' => '102', 'test_type_id' => '184', 'measure_id' => '264'),
			array('id' => '103', 'test_type_id' => '185', 'measure_id' => '265'),
			array('id' => '104', 'test_type_id' => '186', 'measure_id' => '266'),
			array('id' => '105', 'test_type_id' => '187', 'measure_id' => '267'),
			array('id' => '106', 'test_type_id' => '188', 'measure_id' => '268'),
			array('id' => '107', 'test_type_id' => '189', 'measure_id' => '269'),
			array('id' => '108', 'test_type_id' => '190', 'measure_id' => '270'),
			array('id' => '109', 'test_type_id' => '192', 'measure_id' => '272'),
			array('id' => '110', 'test_type_id' => '194', 'measure_id' => '274'),
			array('id' => '111', 'test_type_id' => '195', 'measure_id' => '275'),
			array('id' => '112', 'test_type_id' => '196', 'measure_id' => '276'),
			array('id' => '113', 'test_type_id' => '197', 'measure_id' => '277'),
			array('id' => '114', 'test_type_id' => '198', 'measure_id' => '278'),
			array('id' => '115', 'test_type_id' => '221', 'measure_id' => '284'),
			array('id' => '116', 'test_type_id' => '222', 'measure_id' => '302'),
			array('id' => '117', 'test_type_id' => '223', 'measure_id' => '303'),
			array('id' => '118', 'test_type_id' => '224', 'measure_id' => '304'),
			array('id' => '119', 'test_type_id' => '225', 'measure_id' => '305'),
			array('id' => '120', 'test_type_id' => '226', 'measure_id' => '306'),
			array('id' => '121', 'test_type_id' => '244', 'measure_id' => '322'),
			array('id' => '122', 'test_type_id' => '255', 'measure_id' => '335'),
			array('id' => '123', 'test_type_id' => '260', 'measure_id' => '338'),
			array('id' => '124', 'test_type_id' => '263', 'measure_id' => '282'),
			array('id' => '125', 'test_type_id' => '263', 'measure_id' => '335'),
			array('id' => '126', 'test_type_id' => '263', 'measure_id' => '338'),
			array('id' => '127', 'test_type_id' => '263', 'measure_id' => '343'),
			array('id' => '128', 'test_type_id' => '263', 'measure_id' => '407'),
			array('id' => '129', 'test_type_id' => '265', 'measure_id' => '282'),
			array('id' => '130', 'test_type_id' => '265', 'measure_id' => '335'),
			array('id' => '131', 'test_type_id' => '265', 'measure_id' => '338'),
			array('id' => '132', 'test_type_id' => '265', 'measure_id' => '405'),
			array('id' => '133', 'test_type_id' => '265', 'measure_id' => '406'),
			array('id' => '134', 'test_type_id' => '265', 'measure_id' => '407'),
			array('id' => '135', 'test_type_id' => '267', 'measure_id' => '347'),
			array('id' => '136', 'test_type_id' => '268', 'measure_id' => '302'),
			array('id' => '137', 'test_type_id' => '268', 'measure_id' => '303'),
			array('id' => '138', 'test_type_id' => '268', 'measure_id' => '304'),
			array('id' => '139', 'test_type_id' => '268', 'measure_id' => '305'),
			array('id' => '140', 'test_type_id' => '268', 'measure_id' => '306'),
			array('id' => '141', 'test_type_id' => '271', 'measure_id' => '282'),
			array('id' => '142', 'test_type_id' => '271', 'measure_id' => '322'),
			array('id' => '143', 'test_type_id' => '276', 'measure_id' => '405'),
			array('id' => '144', 'test_type_id' => '276', 'measure_id' => '406'),
			array('id' => '145', 'test_type_id' => '276', 'measure_id' => '407'),
			array('id' => '146', 'test_type_id' => '279', 'measure_id' => '359'),
			array('id' => '147', 'test_type_id' => '281', 'measure_id' => '361'),
			array('id' => '148', 'test_type_id' => '282', 'measure_id' => '362'),
			array('id' => '149', 'test_type_id' => '285', 'measure_id' => '365'),
			array('id' => '150', 'test_type_id' => '287', 'measure_id' => '252'),
			array('id' => '151', 'test_type_id' => '287', 'measure_id' => '282'),
			array('id' => '152', 'test_type_id' => '287', 'measure_id' => '335'),
			array('id' => '153', 'test_type_id' => '287', 'measure_id' => '338'),
			array('id' => '154', 'test_type_id' => '287', 'measure_id' => '403'),
			array('id' => '155', 'test_type_id' => '287', 'measure_id' => '405'),
			array('id' => '156', 'test_type_id' => '287', 'measure_id' => '406'),
			array('id' => '157', 'test_type_id' => '287', 'measure_id' => '407'),
			array('id' => '158', 'test_type_id' => '288', 'measure_id' => '368'),
			array('id' => '159', 'test_type_id' => '289', 'measure_id' => '369'),
			array('id' => '160', 'test_type_id' => '290', 'measure_id' => '370'),
			array('id' => '161', 'test_type_id' => '291', 'measure_id' => '371'),
			array('id' => '162', 'test_type_id' => '292', 'measure_id' => '372'),
			array('id' => '163', 'test_type_id' => '293', 'measure_id' => '373'),
			array('id' => '164', 'test_type_id' => '294', 'measure_id' => '374'),
			array('id' => '165', 'test_type_id' => '295', 'measure_id' => '375'),
			array('id' => '166', 'test_type_id' => '296', 'measure_id' => '376'),
			array('id' => '167', 'test_type_id' => '297', 'measure_id' => '377'),
			array('id' => '168', 'test_type_id' => '298', 'measure_id' => '378'),
			array('id' => '169', 'test_type_id' => '299', 'measure_id' => '379'),
			array('id' => '170', 'test_type_id' => '300', 'measure_id' => '380'),
			array('id' => '171', 'test_type_id' => '301', 'measure_id' => '381'),
			array('id' => '172', 'test_type_id' => '302', 'measure_id' => '382'),
			array('id' => '173', 'test_type_id' => '303', 'measure_id' => '383'),
			array('id' => '174', 'test_type_id' => '304', 'measure_id' => '384'),
			array('id' => '175', 'test_type_id' => '305', 'measure_id' => '385'),
			array('id' => '176', 'test_type_id' => '307', 'measure_id' => '409'),
			array('id' => '177', 'test_type_id' => '308', 'measure_id' => '403'),
			array('id' => '178', 'test_type_id' => '308', 'measure_id' => '404'),
			array('id' => '179', 'test_type_id' => '309', 'measure_id' => '282'),
			array('id' => '180', 'test_type_id' => '309', 'measure_id' => '405'),
			array('id' => '181', 'test_type_id' => '309', 'measure_id' => '406'),
			array('id' => '182', 'test_type_id' => '309', 'measure_id' => '407'),
			array('id' => '183', 'test_type_id' => '310', 'measure_id' => '282'),
			array('id' => '184', 'test_type_id' => '310', 'measure_id' => '407'),
			array('id' => '185', 'test_type_id' => '311', 'measure_id' => '282'),
			array('id' => '186', 'test_type_id' => '311', 'measure_id' => '322'),
			array('id' => '187', 'test_type_id' => '311', 'measure_id' => '405'),
			array('id' => '188', 'test_type_id' => '311', 'measure_id' => '406'),
			array('id' => '189', 'test_type_id' => '312', 'measure_id' => '282'),
			array('id' => '190', 'test_type_id' => '312', 'measure_id' => '407'),
			array('id' => '191', 'test_type_id' => '313', 'measure_id' => '282'),
			array('id' => '192', 'test_type_id' => '313', 'measure_id' => '405'),
			array('id' => '193', 'test_type_id' => '313', 'measure_id' => '406'),
			array('id' => '194', 'test_type_id' => '313', 'measure_id' => '407'),
			array('id' => '195', 'test_type_id' => '314', 'measure_id' => '282'),
			array('id' => '196', 'test_type_id' => '314', 'measure_id' => '407'),
			array('id' => '197', 'test_type_id' => '315', 'measure_id' => '282'),
			array('id' => '198', 'test_type_id' => '315', 'measure_id' => '405'),
			array('id' => '199', 'test_type_id' => '315', 'measure_id' => '406'),
			array('id' => '200', 'test_type_id' => '315', 'measure_id' => '407'),
			array('id' => '201', 'test_type_id' => '316', 'measure_id' => '284'),
			array('id' => '202', 'test_type_id' => '316', 'measure_id' => '405'),
			array('id' => '203', 'test_type_id' => '316', 'measure_id' => '406'),
			array('id' => '204', 'test_type_id' => '317', 'measure_id' => '411'),
			array('id' => '205', 'test_type_id' => '318', 'measure_id' => '405'),
			array('id' => '206', 'test_type_id' => '318', 'measure_id' => '406'),
			array('id' => '207', 'test_type_id' => '319', 'measure_id' => '282'),
			array('id' => '208', 'test_type_id' => '319', 'measure_id' => '405'),
			array('id' => '209', 'test_type_id' => '319', 'measure_id' => '406'),
			array('id' => '210', 'test_type_id' => '319', 'measure_id' => '407'),
			array('id' => '211', 'test_type_id' => '320', 'measure_id' => '282'),
			array('id' => '212', 'test_type_id' => '320', 'measure_id' => '322'),
			array('id' => '213', 'test_type_id' => '320', 'measure_id' => '361'),
			array('id' => '214', 'test_type_id' => '320', 'measure_id' => '362'),
			array('id' => '215', 'test_type_id' => '320', 'measure_id' => '405'),
			array('id' => '216', 'test_type_id' => '320', 'measure_id' => '406'),
			array('id' => '217', 'test_type_id' => '322', 'measure_id' => '350'),
			array('id' => '218', 'test_type_id' => '323', 'measure_id' => '284'),
			array('id' => '219', 'test_type_id' => '323', 'measure_id' => '405'),
			array('id' => '220', 'test_type_id' => '323', 'measure_id' => '406'),
			array('id' => '221', 'test_type_id' => '325', 'measure_id' => '218')
		);
	}

	public static function getTestType()
	{
		return array(
			array('id' => '117', 'name' =>  'Grams stain', 'test_category_id' => '10'),
			array('id' => '118', 'name' =>  'ZN stain', 'test_category_id' => '10'),
			array('id' => '119', 'name' =>  'urine chemistry', 'test_category_id' => '10'),
			array('id' => '120', 'name' =>  'SERUM AMYLASE', 'test_category_id' => '6'),
			array('id' => '121', 'name' =>  'calcium', 'test_category_id' => '6'),
			array('id' => '122', 'name' =>  'CALCIUM', 'test_category_id' => '6'),
			array('id' => '123', 'name' =>  'URIC ACID', 'test_category_id' => '6'),
			array('id' => '124', 'name' =>  'calcium', 'test_category_id' => '6'),
			array('id' => '125', 'name' =>  'Glucose', 'test_category_id' => '6'),
			array('id' => '126', 'name' =>  'Protein', 'test_category_id' => '6'),
			array('id' => '127', 'name' =>  'Ascitic tap for biochemistry', 'test_category_id' => '6'),
			array('id' => '128', 'name' =>  'Glucose', 'test_category_id' => '6'),
			array('id' => '129', 'name' =>  'Protein', 'test_category_id' => '6'),
			array('id' => '130', 'name' =>  'CSF for biochemistry', 'test_category_id' => '6'),
			array('id' => '131', 'name' =>  'PSA', 'test_category_id' => '6'),
			array('id' => '132', 'name' =>  'Total', 'test_category_id' => '6'),
			array('id' => '133', 'name' =>  'Albumin', 'test_category_id' => '6'),
			array('id' => '134', 'name' =>  'Alkaline Phosphate', 'test_category_id' => '6'),
			array('id' => '135', 'name' =>  'ASAT', 'test_category_id' => '6'),
			array('id' => '136', 'name' =>  'SGOT', 'test_category_id' => '6'),
			array('id' => '137', 'name' =>  'ALAT', 'test_category_id' => '6'),
			array('id' => '138', 'name' =>  'Direct ', 'test_category_id' => '6'),
			array('id' => '139', 'name' =>  'Total Proteins ', 'test_category_id' => '6'),
			array('id' => '140', 'name' =>  'Bilirubin', 'test_category_id' => '6'),
			array('id' => '141', 'name' =>  'LFTS', 'test_category_id' => '6'),
			array('id' => '142', 'name' =>  'Chloride', 'test_category_id' => '6'),
			array('id' => '143', 'name' =>  'Potassium', 'test_category_id' => '6'),
			array('id' => '144', 'name' =>  'Sodium', 'test_category_id' => '6'),
			array('id' => '145', 'name' =>  'Electrolytes', 'test_category_id' => '6'),
			array('id' => '146', 'name' =>  'Creatinine ', 'test_category_id' => '6'),
			array('id' => '147', 'name' =>  'Urea', 'test_category_id' => '6'),
			array('id' => '148', 'name' =>  'RFTS', 'test_category_id' => '6'),
			array('id' => '149', 'name' =>  'TFT', 'test_category_id' => '6'),
			array('id' => '150', 'name' =>  'GXM', 'test_category_id' => '13'),
			array('id' => '151', 'name' =>  'Indirect COOMBS test', 'test_category_id' => '13'),
			array('id' => '152', 'name' =>  'Direct COOMBS test', 'test_category_id' => '13'),
			array('id' => '153', 'name' =>  'Du test', 'test_category_id' => '13'),
			array('id' => '154', 'name' =>  'Blood Grouping', 'test_category_id' => '13'),
			array('id' => '155', 'name' =>  'Cross Match', 'test_category_id' => '13'),
			array('id' => '156', 'name' =>  'Epithelial cells', 'test_category_id' => '9'),
			array('id' => '157', 'name' =>  'Urinalysis', 'test_category_id' => '9'),
			array('id' => '158', 'name' =>  'ph', 'test_category_id' => '9'),
			array('id' => '159', 'name' =>  'Blood sugar', 'test_category_id' => '9'),
			array('id' => '160', 'name' =>  'Spermatozoa', 'test_category_id' => '9'),
			array('id' => '161', 'name' =>  'Bacteria', 'test_category_id' => '9'),
			array('id' => '162', 'name' =>  'Red blood cells', 'test_category_id' => '9'),
			array('id' => '163', 'name' =>  'Yeast cells', 'test_category_id' => '9'),
			array('id' => '164', 'name' =>  'T. vaginalis', 'test_category_id' => '9'),
			array('id' => '165', 'name' =>  'S. haematobium', 'test_category_id' => '9'),
			array('id' => '166', 'name' =>  'Pus cells', 'test_category_id' => '9'),
			array('id' => '167', 'name' =>  'Urine microscopy', 'test_category_id' => '9'),
			array('id' => '168', 'name' =>  'HCG', 'test_category_id' => '9'),
			array('id' => '169', 'name' =>  'Urobilinogen Phenlpyruvic acid', 'test_category_id' => '9'),
			array('id' => '170', 'name' =>  'Bilirubin', 'test_category_id' => '9'),
			array('id' => '171', 'name' =>  'Blood', 'test_category_id' => '9'),
			array('id' => '172', 'name' =>  'Proteins', 'test_category_id' => '9'),
			array('id' => '173', 'name' =>  'Ketones', 'test_category_id' => '9'),
			array('id' => '174', 'name' =>  'Glucose', 'test_category_id' => '9'),
			array('id' => '175', 'name' =>  'Urine chemistry', 'test_category_id' => '9'),
			array('id' => '176', 'name' =>  'Full Haemogram', 'test_category_id' => '2'),
			array('id' => '177', 'name' =>  'Eos#', 'test_category_id' => '2'),
			array('id' => '178', 'name' =>  'Mon#', 'test_category_id' => '2'),
			array('id' => '179', 'name' =>  'Lym#', 'test_category_id' => '2'),
			array('id' => '180', 'name' =>  'Neu#', 'test_category_id' => '2'),
			array('id' => '181', 'name' =>  'WBC', 'test_category_id' => '2'),
			array('id' => '182', 'name' =>  'RBC', 'test_category_id' => '2'),
			array('id' => '183', 'name' =>  'HB', 'test_category_id' => '2'),
			array('id' => '184', 'name' =>  'HCT', 'test_category_id' => '2'),
			array('id' => '185', 'name' =>  'MCV', 'test_category_id' => '2'),
			array('id' => '186', 'name' =>  'MCH', 'test_category_id' => '2'),
			array('id' => '187', 'name' =>  'MCHC', 'test_category_id' => '2'),
			array('id' => '188', 'name' =>  'RDW', 'test_category_id' => '2'),
			array('id' => '189', 'name' =>  'PLATELET COUNT', 'test_category_id' => '2'),
			array('id' => '190', 'name' =>  'PCT', 'test_category_id' => '2'),
			array('id' => '191', 'name' =>  'MPV', 'test_category_id' => '2'),
			array('id' => '192', 'name' =>  'PDW', 'test_category_id' => '2'),
			array('id' => '193', 'name' =>  'Full Haemogram', 'test_category_id' => '2'),
			array('id' => '194', 'name' =>  'Bleeding time test', 'test_category_id' => '2'),
			array('id' => '195', 'name' =>  'Clotting time test', 'test_category_id' => '2'),
			array('id' => '196', 'name' =>  'PTI/INR', 'test_category_id' => '2'),
			array('id' => '197', 'name' =>  'Sickling test', 'test_category_id' => '2'),
			array('id' => '198', 'name' =>  'ESR', 'test_category_id' => '2'),
			array('id' => '199', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '200', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '201', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '202', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '203', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '204', 'name' =>  'microscopy', 'test_category_id' => '7'),
			array('id' => '205', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '206', 'name' =>  'zn stain', 'test_category_id' => '7'),
			array('id' => '207', 'name' =>  'gramstain', 'test_category_id' => '7'),
			array('id' => '208', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '209', 'name' =>  'gramstain', 'test_category_id' => '7'),
			array('id' => '210', 'name' =>  'urine chemistry', 'test_category_id' => '7'),
			array('id' => '211', 'name' =>  'microscopy', 'test_category_id' => '7'),
			array('id' => '212', 'name' =>  'urine chemistry', 'test_category_id' => '7'),
			array('id' => '213', 'name' =>  'gramstain', 'test_category_id' => '7'),
			array('id' => '214', 'name' =>  'SENSITIVITY', 'test_category_id' => '7'),
			array('id' => '215', 'name' =>  'CULTURE', 'test_category_id' => '7'),
			array('id' => '216', 'name' =>  'gRAMSTAIN', 'test_category_id' => '7'),
			array('id' => '217', 'name' =>  'zn STAIN ', 'test_category_id' => '7'),
			array('id' => '218', 'name' =>  'Throat swab for culture', 'test_category_id' => '7'),
			array('id' => '219', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '220', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '221', 'name' =>  'microscopy', 'test_category_id' => '7'),
			array('id' => '222', 'name' =>  'microscopic examination', 'test_category_id' => '7'),
			array('id' => '223', 'name' =>  'sperm count', 'test_category_id' => '7'),
			array('id' => '224', 'name' =>  'motility', 'test_category_id' => '7'),
			array('id' => '225', 'name' =>  'viscosity', 'test_category_id' => '7'),
			array('id' => '226', 'name' =>  'volume', 'test_category_id' => '7'),
			array('id' => '227', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '228', 'name' =>  'CULTURE', 'test_category_id' => '7'),
			array('id' => '229', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '230', 'name' =>  'ZN STAIN', 'test_category_id' => '7'),
			array('id' => '231', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '232', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '233', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '234', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '235', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '236', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '237', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '238', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '239', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '240', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '241', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '242', 'name' =>  'wet prep', 'test_category_id' => '7'),
			array('id' => '243', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '244', 'name' =>  'wet prep', 'test_category_id' => '7'),
			array('id' => '245', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '246', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '247', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '248', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '249', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '250', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '251', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '252', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '253', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '254', 'name' =>  'culture ', 'test_category_id' => '7'),
			array('id' => '255', 'name' =>  'Indian ink', 'test_category_id' => '7'),
			array('id' => '256', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '257', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '258', 'name' =>  'cell count', 'test_category_id' => '7'),
			array('id' => '259', 'name' =>  'Indian ink', 'test_category_id' => '7'),
			array('id' => '260', 'name' =>  'cell count', 'test_category_id' => '7'),
			array('id' => '261', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '262', 'name' =>  'Gramstain ', 'test_category_id' => '7'),
			array('id' => '263', 'name' =>  'culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '264', 'name' =>  'microscopy', 'test_category_id' => '7'),
			array('id' => '265', 'name' =>  'CSF for microbiology', 'test_category_id' => '7'),
			array('id' => '266', 'name' =>  'Pus swab for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '267', 'name' =>  'KOH for fungi', 'test_category_id' => '7'),
			array('id' => '268', 'name' =>  'semen analysis', 'test_category_id' => '7'),
			array('id' => '269', 'name' =>  'Aspirate for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '270', 'name' =>  'Aspirate for microscopy ', 'test_category_id' => '7'),
			array('id' => '271', 'name' =>  'HVS for microscopy ', 'test_category_id' => '7'),
			array('id' => '272', 'name' =>  'Synovial fluid for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '273', 'name' =>  'Synovial fluid for microscopy', 'test_category_id' => '7'),
			array('id' => '274', 'name' =>  'Pleural tap for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '275', 'name' =>  'Pleural tap for microscopy', 'test_category_id' => '7'),
			array('id' => '276', 'name' =>  'Ascitic tap for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '277', 'name' =>  'Ascitic tap for microscopy', 'test_category_id' => '7'),
			array('id' => '278', 'name' =>  'Urine Culture & Sensitivity', 'test_category_id' => '7'),
			array('id' => '279', 'name' =>  'Water Analysis', 'test_category_id' => '7'),
			array('id' => '280', 'name' =>  'Wet prep', 'test_category_id' => '7'),
			array('id' => '281', 'name' =>  'Gram stain', 'test_category_id' => '7'),
			array('id' => '282', 'name' =>  'Sub culture ', 'test_category_id' => '7'),
			array('id' => '283', 'name' =>  'Blood Culture & sensitivity', 'test_category_id' => '7'),
			array('id' => '284', 'name' =>  'HVS for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '285', 'name' =>  'Sputum', 'test_category_id' => '7'),
			array('id' => '286', 'name' =>  'Stool for C/S', 'test_category_id' => '7'),
			array('id' => '287', 'name' =>  'CSF', 'test_category_id' => '8'),
			array('id' => '288', 'name' =>  'salmonella antigen test', 'test_category_id' => '12'),
			array('id' => '289', 'name' =>  'OCCULT BLOOD', 'test_category_id' => '12'),
			array('id' => '290', 'name' =>  'Stool for O/C', 'test_category_id' => '12'),
			array('id' => '291', 'name' =>  'BS for mps', 'test_category_id' => '12'),
			array('id' => '292', 'name' =>  'Borrelia', 'test_category_id' => '12'),
			array('id' => '293', 'name' =>  'PBF', 'test_category_id' => '1'),
			array('id' => '294', 'name' =>  'HEPATITIS C', 'test_category_id' => '1'),
			array('id' => '295', 'name' =>  'HEPATITIS B', 'test_category_id' => '1'),
			array('id' => '296', 'name' =>  'Asot Titration', 'test_category_id' => '1'),
			array('id' => '297', 'name' =>  'Widal Titration', 'test_category_id' => '1'),
			array('id' => '298', 'name' =>  'VDRL', 'test_category_id' => '1'),
			array('id' => '299', 'name' =>  'Asot', 'test_category_id' => '1'),
			array('id' => '300', 'name' =>  'Pregnancy test', 'test_category_id' => '1'),
			array('id' => '301', 'name' =>  'RF', 'test_category_id' => '1'),
			array('id' => '302', 'name' =>  'Brucella', 'test_category_id' => '1'),
			array('id' => '303', 'name' =>  'Widal', 'test_category_id' => '1'),
			array('id' => '304', 'name' =>  'H pylori', 'test_category_id' => '1'),
			array('id' => '305', 'name' =>  'CD4', 'test_category_id' => '4'),
			array('id' => '306', 'name' =>  'Full Haemogram', 'test_category_id' => '6'),
			array('id' => '307', 'name' =>  'Albumin', 'test_category_id' => '1'),
			array('id' => '308', 'name' =>  'CSF for biochemistry', 'test_category_id' => '6'),
			array('id' => '309', 'name' =>  'Throat swab for culture', 'test_category_id' => '7'),
			array('id' => '310', 'name' =>  'Ascitic tap for microscopy', 'test_category_id' => '7'),
			array('id' => '311', 'name' =>  'HVS for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '312', 'name' =>  'Synovial fluid for microscopy', 'test_category_id' => '7'),
			array('id' => '313', 'name' =>  'Pleural tap for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '314', 'name' =>  'Pleural tap for microscopy', 'test_category_id' => '7'),
			array('id' => '315', 'name' =>  'Synovial fluid for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '316', 'name' =>  'Stool for C/S', 'test_category_id' => '7'),
			array('id' => '317', 'name' =>  'Aspirate for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '318', 'name' =>  'Urine Culture and Sensitivity ', 'test_category_id' => '7'),
			array('id' => '319', 'name' =>  'Pus swab for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '320', 'name' =>  'Blood Culture and sensitivity ', 'test_category_id' => '7'),
			array('id' => '321', 'name' =>  ' Aspirate for microscopy ', 'test_category_id' => '7'),
			array('id' => '322', 'name' =>  'Aspirate for microscopy', 'test_category_id' => '7'),
			array('id' => '323', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '324', 'name' =>  'Manual WBC Count', 'test_category_id' => '8'),
			array('id' => '325', 'name' =>  'aPTT', 'test_category_id' => '6')
		);
	}

	public static function getTesttypeSpecimentype()
	{
		return array(
			array('150', '6'),
			array('151', '6'),
			array('152', '6'),
			array('153', '6'),
			array('154', '6'),
			array('155', '6'),
			array('176', '6'),
			array('181', '6'),
			array('182', '6'),
			array('183', '6'),
			array('184', '6'),
			array('185', '6'),
			array('186', '6'),
			array('187', '6'),
			array('188', '6'),
			array('189', '6'),
			array('190', '6'),
			array('191', '6'),
			array('192', '6'),
			array('194', '6'),
			array('195', '6'),
			array('196', '6'),
			array('197', '6'),
			array('198', '6'),
			array('281', '6'),
			array('282', '6'),
			array('291', '6'),
			array('292', '6'),
			array('293', '6'),
			array('305', '6'),
			array('159', '6'),
			array('320', '6'),
			array('120', '7'),
			array('123', '7'),
			array('124', '7'),
			array('131', '7'),
			array('132', '7'),
			array('134', '7'),
			array('135', '7'),
			array('136', '7'),
			array('137', '7'),
			array('138', '7'),
			array('139', '7'),
			array('141', '7'),
			array('142', '7'),
			array('143', '7'),
			array('144', '7'),
			array('145', '7'),
			array('146', '7'),
			array('147', '7'),
			array('148', '7'),
			array('149', '7'),
			array('288', '7'),
			array('294', '7'),
			array('295', '7'),
			array('296', '7'),
			array('297', '7'),
			array('298', '7'),
			array('299', '7'),
			array('301', '7'),
			array('302', '7'),
			array('303', '7'),
			array('304', '7'),
			array('307', '7'),
			array('285', '9'),
			array('255', '10'),
			array('260', '10'),
			array('263', '10'),
			array('265', '10'),
			array('287', '10'),
			array('308', '10'),
			array('156', '11'),
			array('157', '11'),
			array('158', '11'),
			array('160', '11'),
			array('161', '11'),
			array('162', '11'),
			array('163', '11'),
			array('164', '11'),
			array('165', '11'),
			array('166', '11'),
			array('167', '11'),
			array('168', '11'),
			array('169', '11'),
			array('170', '11'),
			array('172', '11'),
			array('173', '11'),
			array('174', '11'),
			array('175', '11'),
			array('300', '11'),
			array('318', '11'),
			array('221', '12'),
			array('289', '12'),
			array('290', '12'),
			array('288', '12'),
			array('323', '12'),
			array('117', '13'),
			array('317', '13'),
			array('322', '13'),
			array('222', '15'),
			array('223', '15'),
			array('224', '15'),
			array('225', '15'),
			array('226', '15'),
			array('268', '15'),
			array('309', '17'),
			array('267', '22'),
			array('244', '25'),
			array('271', '25'),
			array('311', '25'),
			array('126', '26'),
			array('127', '26'),
			array('276', '26'),
			array('310', '26'),
			array('312', '27'),
			array('315', '27'),
			array('316', '27'),
			array('313', '28'),
			array('314', '28'),
			array('279', '29'),
			array('319', '30')
		);
	}

	public static function getUser()
	{
		return array(
			array('id' => '1', 'username' => 'administrator', 'password' => Hash::make('password'), 'name' => 'kBLIS Administrator', 'email' => 'admin@kblis.org'),
			array('id' => '2', 'username' => 'shila', 'password' => Hash::make('shila'), 'name' => 'Shila Alpert', 'email' => ''),
			array('id' => '3', 'username' => 'alec', 'password' => Hash::make('alec'), 'name' => 'Alec Mesa', 'email' => 'none@mail.com'),
			array('id' => '4', 'username' => 'mable', 'password' => Hash::make('mable'), 'name' => 'Mable Vidal', 'email' => 'none@mail.com'),
			array('id' => '5', 'username' => 'zetta', 'password' => Hash::make('zetta'), 'name' => 'Zetta Hesler', 'email' => ''),
			array('id' => '6', 'username' => 'nathanial', 'password' => Hash::make('nathanial'), 'name' => 'Nathanial Poplar', 'email' => 'none@mail.com'),
			array('id' => '7', 'username' => 'soraya', 'password' => Hash::make('soraya'), 'name' => 'Soraya Meares', 'email' => 'none@mail.com'),
			array('id' => '8', 'username' => 'karmen', 'password' => Hash::make('karmen'), 'name' => 'Karmen Hinton', 'email' => ''),
			array('id' => '9', 'username' => 'peggie', 'password' => Hash::make('peggie'), 'name' => 'Peggie Waldrup', 'email' => 'none@mail.com'),
			array('id' => '10', 'username' => 'ute', 'password' => Hash::make('ute'), 'name' => 'Ute Damiano', 'email' => ''),
			array('id' => '11', 'username' => 'marietta', 'password' => Hash::make('marietta'), 'name' => 'Marietta Lama', 'email' => 'none@mail.com'),
			array('id' => '12', 'username' => 'jaquelyn', 'password' => Hash::make('jaquelyn'), 'name' => 'Jaquelyn Huntley', 'email' => 'none@mail.com'),
			array('id' => '13', 'username' => 'laverna', 'password' => Hash::make('laverna'), 'name' => 'Laverna Crooms', 'email' => 'none@mail.com'),
			array('id' => '14', 'username' => 'angelica', 'password' => Hash::make('angelica'), 'name' => 'Angelica Clarkson', 'email' => 'none@mail.com'),
			array('id' => '15', 'username' => 'kermit', 'password' => Hash::make('kermit'), 'name' => 'Kermit Widman', 'email' => 'none@mail.com'),
			array('id' => '16', 'username' => 'nikole', 'password' => Hash::make('nikole'), 'name' => 'Nikole Witmer', 'email' => 'none@mail.com'),
			array('id' => '17', 'username' => 'fausto', 'password' => Hash::make('fausto'), 'name' => 'Fausto Quijada', 'email' => 'none@mail.com'),
			array('id' => '18', 'username' => 'robbin', 'password' => Hash::make('robbin'), 'name' => 'Robbin Yaple', 'email' => 'beatricelungai@yahoo.com'),
			array('id' => '19', 'username' => 'kyong', 'password' => Hash::make('kyong'), 'name' => 'Kyong Echevarria', 'email' => 'none@mail.com'),
			array('id' => '20', 'username' => 'leila', 'password' => Hash::make('leila'), 'name' => 'Leila Goya', 'email' => 'none@mail.com'),
			array('id' => '21', 'username' => 'carlee', 'password' => Hash::make('carlee'), 'name' => 'Carlee Curren', 'email' => 'none@mail.com'),
			array('id' => '22', 'username' => 'lakita', 'password' => Hash::make('lakita'), 'name' => 'Lakita Mcgonigal', 'email' => 'none@mail.com'),
			array('id' => '23', 'username' => 'evon', 'password' => Hash::make('evon'), 'name' => 'Evon Noss', 'email' => ''),
			array('id' => '24', 'username' => 'elenor', 'password' => Hash::make('elenor'), 'name' => 'Elenor Natoli', 'email' => 'none@mail.com'),
			array('id' => '25', 'username' => 'shakira', 'password' => Hash::make('shakira'), 'name' => 'Shakira Saia', 'email' => 'none@mail.com'),
			array('id' => '26', 'username' => 'kathline', 'password' => Hash::make('kathline'), 'name' => 'Kathline Alsobrook', 'email' => 'none@mail.com'),
			array('id' => '27', 'username' => 'sheryll', 'password' => Hash::make('sheryll'), 'name' => 'Sheryll Lepley', 'email' => 'none@mail.com'),
			array('id' => '28', 'username' => 'lucie', 'password' => Hash::make('lucie'), 'name' => 'Lucie Banh', 'email' => 'none@mail.com'),
			array('id' => '29', 'username' => 'tasha', 'password' => Hash::make('tasha'), 'name' => 'Tasha Benfield', 'email' => 'none@mail.com'),
			array('id' => '30', 'username' => 'nigel', 'password' => Hash::make('nigel'), 'name' => 'Nigel Mace', 'email' => 'none@mail.com'),
			array('id' => '31', 'username' => 'bernie', 'password' => Hash::make('bernie'), 'name' => 'Bernie Carini', 'email' => 'none@mail.com'),
			array('id' => '32', 'username' => 'jeneva', 'password' => Hash::make('jeneva'), 'name' => 'Jeneva Harari', 'email' => 'none@mail.com'),
			array('id' => '33', 'username' => 'bert', 'password' => Hash::make('bert'), 'name' => 'Bert Hirai', 'email' => 'none@mail.com'),
			array('id' => '34', 'username' => 'nick', 'password' => Hash::make('nick'), 'name' => 'Nick Peil', 'email' => 'none@mail.com'),
			array('id' => '35', 'username' => 'milda', 'password' => Hash::make('milda'), 'name' => 'Milda Clara', 'email' => 'none@mail.com'),
			array('id' => '36', 'username' => 'yun', 'password' => Hash::make('yun'), 'name' => 'Yun Labrecque', 'email' => 'none@mail.com'),
			array('id' => '37', 'username' => 'dora', 'password' => Hash::make('dora'), 'name' => 'Dora Hathcock', 'email' => 'none@mail.com'),
			array('id' => '38', 'username' => 'cheryle', 'password' => Hash::make('cheryle'), 'name' => 'Cheryle Izquierdo', 'email' => 'none@mail.com'),
			array('id' => '39', 'username' => 'jaleesa', 'password' => Hash::make('jaleesa'), 'name' => 'Jaleesa Hayes', 'email' => 'none@mail.com'),
			array('id' => '40', 'username' => 'nena', 'password' => Hash::make('nena'), 'name' => 'Nena Mccluney', 'email' => 'none@mail.com'),
			array('id' => '41', 'username' => 'lidia', 'password' => Hash::make('lidia'), 'name' => 'Lidia Furst', 'email' => 'none@mail.com'),
			array('id' => '42', 'username' => 'james', 'password' => Hash::make('james'), 'name' => 'James Reindl', 'email' => 'none@mail.com'),
			array('id' => '43', 'username' => 'ayako', 'password' => Hash::make('ayako'), 'name' => 'Ayako Petrie', 'email' => ''),
			array('id' => '44', 'username' => 'tanna', 'password' => Hash::make('tanna'), 'name' => 'Tanna Yelvington', 'email' => 'none@mail.com'),
			array('id' => '45', 'username' => 'lois', 'password' => Hash::make('lois'), 'name' => 'Lois Klapp', 'email' => 'none@mail.com'),
			array('id' => '46', 'username' => 'danuta', 'password' => Hash::make('danuta'), 'name' => 'Danuta Aust', 'email' => 'none@mail.com'),
			array('id' => '47', 'username' => 'carlie', 'password' => Hash::make('carlie'), 'name' => 'Carlie Goyette', 'email' => 'none@mail.com'),
			array('id' => '48', 'username' => 'clarisa', 'password' => Hash::make('clarisa'), 'name' => 'Clarisa Richeson', 'email' => 'none@mail.com'),
			array('id' => '49', 'username' => 'fidelia', 'password' => Hash::make('fidelia'), 'name' => 'Fidelia Dorminey', 'email' => 'none@mail.com'),
			array('id' => '50', 'username' => 'nadine', 'password' => Hash::make('nadine'), 'name' => 'Nadine Hoggard', 'email' => 'none@mail.com'),
			array('id' => '51', 'username' => 'oliva', 'password' => Hash::make('oliva'), 'name' => 'Oliva Craghead', 'email' => 'none@mail.com'),
			array('id' => '52', 'username' => 'marna', 'password' => Hash::make('marna'), 'name' => 'Marna Amezquita', 'email' => 'none@mail.com'),
			array('id' => '53', 'username' => 'wallace', 'password' => Hash::make('wallace'), 'name' => 'Wallace Petite', 'email' => 'none@mail.com'),
			array('id' => '54', 'username' => 'gwen', 'password' => Hash::make('gwen'), 'name' => 'Gwen Liss', 'email' => 'none@mail.com'),
			array('id' => '55', 'username' => 'joie', 'password' => Hash::make('joie'), 'name' => 'Joie Deets', 'email' => 'none@mail.com'),
			array('id' => '56', 'username' => 'kenyatta', 'password' => Hash::make('kenyatta'), 'name' => 'Kenyatta Goosby', 'email' => 'none@mail.com'),
			array('id' => '57', 'username' => 'cameron', 'password' => Hash::make('cameron'), 'name' => 'Cameron Book', 'email' => 'none@mail.com'),
			array('id' => '58', 'username' => 'deloris', 'password' => Hash::make('deloris'), 'name' => 'Deloris Fix', 'email' => 'none@mail.com'),
			array('id' => '59', 'username' => 'robbyn', 'password' => Hash::make('robbyn'), 'name' => 'Robbyn Sturgill', 'email' => 'none@mail.com'),
			array('id' => '60', 'username' => 'etsuko', 'password' => Hash::make('etsuko'), 'name' => 'Etsuko Thornhill', 'email' => 'none@mail.com'),
			array('id' => '61', 'username' => 'ivory', 'password' => Hash::make('ivory'), 'name' => 'Ivory Hippler', 'email' => 'none@mail.com'),
			array('id' => '62', 'username' => 'shena', 'password' => Hash::make('shena'), 'name' => 'Shena Nakamura', 'email' => 'none@mail.com'),
			array('id' => '63', 'username' => 'gertrude', 'password' => Hash::make('gertrude'), 'name' => 'Gertrude Carini', 'email' => 'none@mail.com'),
			array('id' => '64', 'username' => 'agripina', 'password' => Hash::make('agripina'), 'name' => 'Agripina Schultze', 'email' => 'none@mail.com'),
			array('id' => '65', 'username' => 'shela', 'password' => Hash::make('shela'), 'name' => 'Shela Mabee', 'email' => 'none@mail.com'),
			array('id' => '66', 'username' => 'ciara', 'password' => Hash::make('ciara'), 'name' => 'Ciara Ginsberg', 'email' => 'none@mail.com'),
			array('id' => '67', 'username' => 'luigi', 'password' => Hash::make('luigi'), 'name' => 'Luigi Young', 'email' => 'none@mail.com'),
			array('id' => '68', 'username' => 'alfreda', 'password' => Hash::make('alfreda'), 'name' => 'Alfreda Lowman', 'email' => 'none@mail.com'),
			array('id' => '69', 'username' => 'nia', 'password' => Hash::make('nia'), 'name' => 'Nia Ferrer', 'email' => 'none@mail.com'),
			array('id' => '70', 'username' => 'louise', 'password' => Hash::make('louise'), 'name' => 'Louise Wheelock', 'email' => 'none@mail.com'),
			array('id' => '71', 'username' => 'shalonda', 'password' => Hash::make('shalonda'), 'name' => 'Shalonda Greeson', 'email' => 'none@mail.com'),
			array('id' => '72', 'username' => 'peggy', 'password' => Hash::make('peggy'), 'name' => 'Peggy Welte', 'email' => 'none@mail.com'),
			array('id' => '73', 'username' => 'miguel', 'password' => Hash::make('miguel'), 'name' => 'Miguel Mccallum', 'email' => 'none@mail.com'),
			array('id' => '74', 'username' => 'devorah', 'password' => Hash::make('devorah'), 'name' => 'Devorah Holiday', 'email' => 'none@mail.com'),
			array('id' => '75', 'username' => 'faustino', 'password' => Hash::make('faustino'), 'name' => 'Faustino Roux', 'email' => 'none@mail.com'),
			array('id' => '76', 'username' => 'eric', 'password' => Hash::make('eric'), 'name' => 'Eric Milledge', 'email' => 'none@mail.com'),
			array('id' => '77', 'username' => 'isaac', 'password' => Hash::make('isaac'), 'name' => 'Isaac Waddell', 'email' => 'none@mail.com'),
			array('id' => '78', 'username' => 'elise', 'password' => Hash::make('elise'), 'name' => 'Elise Immel', 'email' => 'none@mail.com'),
			array('id' => '79', 'username' => 'karissa', 'password' => Hash::make('karissa'), 'name' => 'Karissa Brasher', 'email' => 'none@mail.com'),
			array('id' => '80', 'username' => 'june', 'password' => Hash::make('june'), 'name' => 'June Fortuna', 'email' => 'none@mail.com'),
			array('id' => '81', 'username' => 'sabra', 'password' => Hash::make('sabra'), 'name' => 'Sabra Guin', 'email' => 'none@mail.com'),
			array('id' => '82', 'username' => 'afton', 'password' => Hash::make('afton'), 'name' => 'Afton Hauge', 'email' => 'none@mail.com'),
			array('id' => '83', 'username' => 'otelia', 'password' => Hash::make('otelia'), 'name' => 'Otelia Griffiths', 'email' => 'none@mail.com'),
			array('id' => '84', 'username' => 'jeffry', 'password' => Hash::make('jeffry'), 'name' => 'Jeffry Carmean', 'email' => 'none@mail.com'),
			array('id' => '85', 'username' => 'emmie', 'password' => Hash::make('emmie'), 'name' => 'Emmie Hodson', 'email' => 'none@mail.com'),
			array('id' => '86', 'username' => 'lamar', 'password' => Hash::make('lamar'), 'name' => 'Lamar Stegner', 'email' => 'none@mail.com'),
			array('id' => '87', 'username' => 'deon', 'password' => Hash::make('deon'), 'name' => 'Deon Mo', 'email' => 'none@mail.com'),
			array('id' => '88', 'username' => 'sharleen', 'password' => Hash::make('sharleen'), 'name' => 'Sharleen Vandiver', 'email' => 'none@mail.com'),
			array('id' => '89', 'username' => 'germaine', 'password' => Hash::make('germaine'), 'name' => 'Germaine Battey', 'email' => 'none@mail.com'),
			array('id' => '90', 'username' => 'marian', 'password' => Hash::make('marian'), 'name' => 'Marian Whitner', 'email' => 'none@mail.com'),
			array('id' => '91', 'username' => 'leoma', 'password' => Hash::make('leoma'), 'name' => 'Leoma Leo', 'email' => 'none@mail.com'),
			array('id' => '92', 'username' => 'stacy', 'password' => Hash::make('stacy'), 'name' => 'Stacy Salone', 'email' => 'none@mail.com'),
			array('id' => '93', 'username' => 'nicolasa', 'password' => Hash::make('nicolasa'), 'name' => 'Nicolasa Bitting', 'email' => 'none@mail.com'),
			array('id' => '94', 'username' => 'nicki', 'password' => Hash::make('nicki'), 'name' => 'Nicki Wilford', 'email' => 'none@mail.com'),
			array('id' => '95', 'username' => 'roderick', 'password' => Hash::make('roderick'), 'name' => 'Roderick Freeland', 'email' => 'none@mail.com'),
			array('id' => '96', 'username' => 'teddy', 'password' => Hash::make('teddy'), 'name' => 'Teddy Thurgood', 'email' => 'none@mail.com'),
			array('id' => '97', 'username' => 'todd', 'password' => Hash::make('todd'), 'name' => 'Todd Corbell', 'email' => 'none@mail.com'),
			array('id' => '98', 'username' => 'therese', 'password' => Hash::make('therese'), 'name' => 'Therese Hippe', 'email' => 'none@mail.com'),
			array('id' => '99', 'username' => 'maryetta', 'password' => Hash::make('maryetta'), 'name' => 'Maryetta Culbreth', 'email' => 'none@mail.com'),
			array('id' => '100', 'username' => 'clifton', 'password' => Hash::make('clifton'), 'name' => 'Clifton Walmsley', 'email' => 'none@mail.com'),
			array('id' => '101', 'username' => 'zona', 'password' => Hash::make('zona'), 'name' => 'Zona Toye', 'email' => 'none@mail.com'),
			array('id' => '102', 'username' => 'derrick', 'password' => Hash::make('derrick'), 'name' => 'Derrick Poor', 'email' => 'none@mail.com'),
			array('id' => '103', 'username' => 'oscar', 'password' => Hash::make('oscar'), 'name' => 'Oscar Disalvo', 'email' => 'none@mail.com'),
			array('id' => '104', 'username' => 'scotty', 'password' => Hash::make('scotty'), 'name' => 'Scotty Messmer', 'email' => 'none@mail.com'),
			array('id' => '105', 'username' => 'phyliss', 'password' => Hash::make('phyliss'), 'name' => 'Phyliss Joines', 'email' => 'none@mail.com'),
			array('id' => '106', 'username' => 'migdalia', 'password' => Hash::make('migdalia'), 'name' => 'Migdalia Pouliot', 'email' => 'none@mail.com'),
			array('id' => '107', 'username' => 'dana', 'password' => Hash::make('dana'), 'name' => 'Dana Raposo', 'email' => 'none@mail.com'),
			array('id' => '108', 'username' => 'preston', 'password' => Hash::make('preston'), 'name' => 'Preston Champagne', 'email' => 'none@mail.com'),
			array('id' => '109', 'username' => 'daryl', 'password' => Hash::make('daryl'), 'name' => 'Daryl Hamilton', 'email' => 'none@mail.com'),
			array('id' => '110', 'username' => 'johnson', 'password' => Hash::make('johnson'), 'name' => 'Johnson Bateman', 'email' => 'none@mail.com'),
			array('id' => '111', 'username' => 'jerrold', 'password' => Hash::make('jerrold'), 'name' => 'Jerrold Pigram', 'email' => 'none@mail.com'),
			array('id' => '112', 'username' => 'fernanda', 'password' => Hash::make('fernanda'), 'name' => 'Fernanda Degregorio', 'email' => 'none@mail.com'),
			array('id' => '113', 'username' => 'shala', 'password' => Hash::make('shala'), 'name' => 'Shala Shupp', 'email' => 'none@mail.com'),
			array('id' => '114', 'username' => 'tomoko', 'password' => Hash::make('tomoko'), 'name' => 'Tomoko Korth', 'email' => 'none@mail.com'),
			array('id' => '115', 'username' => 'adolfo', 'password' => Hash::make('adolfo'), 'name' => 'Adolfo Harvin', 'email' => 'none@mail.com'),
			array('id' => '116', 'username' => 'madeline', 'password' => Hash::make('madeline'), 'name' => 'Madeline Kincer', 'email' => 'none@mail.com'),
			array('id' => '117', 'username' => 'garry', 'password' => Hash::make('garry'), 'name' => 'Garry Golding', 'email' => 'none@mail.com'),
			array('id' => '118', 'username' => 'darryl', 'password' => Hash::make('darryl'), 'name' => 'Darryl Haskins', 'email' => 'none@mail.com'),
			array('id' => '119', 'username' => 'ina', 'password' => Hash::make('ina'), 'name' => 'Ina Berkowitz', 'email' => 'none@mail.com'),
			array('id' => '120', 'username' => 'georgene', 'password' => Hash::make('georgene'), 'name' => 'Georgene Rieser', 'email' => 'none@mail.com'),
			array('id' => '121', 'username' => 'soledad', 'password' => Hash::make('soledad'), 'name' => 'Soledad Neth', 'email' => 'none@mail.com'),
			array('id' => '122', 'username' => 'jayme', 'password' => Hash::make('jayme'), 'name' => 'Jayme Dykema', 'email' => 'none@mail.com'),
			array('id' => '123', 'username' => 'cindi', 'password' => Hash::make('cindi'), 'name' => 'Cindi Greenway', 'email' => 'none@mail.com'),
			array('id' => '124', 'username' => 'kenisha', 'password' => Hash::make('kenisha'), 'name' => 'Kenisha Jaso', 'email' => 'none@mail.com'),
			array('id' => '125', 'username' => 'ashton', 'password' => Hash::make('ashton'), 'name' => 'Ashton Allgeier', 'email' => 'none@mail.com'),
			array('id' => '126', 'username' => 'calandra', 'password' => Hash::make('calandra'), 'name' => 'Calandra Blick', 'email' => 'none@mail.com'),
			array('id' => '127', 'username' => 'jonas', 'password' => Hash::make('jonas'), 'name' => 'Jonas Sander', 'email' => 'none@mail.com'),
			array('id' => '128', 'username' => 'samuel', 'password' => Hash::make('samuel'), 'name' => 'Samuel Gomer', 'email' => 'none@mail.com'),
			array('id' => '129', 'username' => 'sterling', 'password' => Hash::make('sterling'), 'name' => 'Sterling Noland', 'email' => 'none@mail.com'),
			array('id' => '130', 'username' => 'lorrine', 'password' => Hash::make('lorrine'), 'name' => 'Lorrine Rafferty', 'email' => 'none@mail.com'),
			array('id' => '131', 'username' => 'catalina', 'password' => Hash::make('catalina'), 'name' => 'Catalina Golden', 'email' => 'none@mail.com'),
			array('id' => '132', 'username' => 'nida', 'password' => Hash::make('nida'), 'name' => 'Nida Balicki', 'email' => 'none@mail.com'),
			array('id' => '133', 'username' => 'awilda', 'password' => Hash::make('awilda'), 'name' => 'Awilda Strobel', 'email' => 'none@mail.com'),
			array('id' => '134', 'username' => 'catherina', 'password' => Hash::make('catherina'), 'name' => 'Catherina Bluhm', 'email' => 'none@mail.com'),
			array('id' => '135', 'username' => 'marcy', 'password' => Hash::make('marcy'), 'name' => 'Marcy Miramontes', 'email' => 'none@mail.com'),
			array('id' => '136', 'username' => 'maren', 'password' => Hash::make('maren'), 'name' => 'Maren Notaro', 'email' => ''),
			array('id' => '137', 'username' => 'evan', 'password' => Hash::make('evan'), 'name' => 'Evan Alberico', 'email' => 'none@mail.com'),
			array('id' => '138', 'username' => 'lurlene', 'password' => Hash::make('lurlene'), 'name' => 'Lurlene Cote', 'email' => 'none@mail.com'),
			array('id' => '139', 'username' => 'eldon', 'password' => Hash::make('eldon'), 'name' => 'Eldon Kravetz', 'email' => 'none@mail.com'),
			array('id' => '140', 'username' => 'joanna', 'password' => Hash::make('joanna'), 'name' => 'Joanna Viernes', 'email' => 'none@mail.com'),
			array('id' => '141', 'username' => 'terry', 'password' => Hash::make('terry'), 'name' => 'Terry Woodrow', 'email' => 'none@mail.com'),
			array('id' => '142', 'username' => 'charleen', 'password' => Hash::make('charleen'), 'name' => 'Charleen Wyrick', 'email' => 'none@mail.com'),
			array('id' => '143', 'username' => 'cathey', 'password' => Hash::make('cathey'), 'name' => 'Cathey Culpepper', 'email' => 'none@mail.com'),
			array('id' => '144', 'username' => 'roxana', 'password' => Hash::make('roxana'), 'name' => 'Roxana Yoder', 'email' => 'none@mail.com'),
			array('id' => '145', 'username' => 'shanell', 'password' => Hash::make('shanell'), 'name' => 'Shanell Chesser', 'email' => 'none@mail.com'),
			array('id' => '146', 'username' => 'rolanda', 'password' => Hash::make('rolanda'), 'name' => 'Rolanda Aguillard', 'email' => 'none@mail.com'),
			array('id' => '147', 'username' => 'cheryl', 'password' => Hash::make('cheryl'), 'name' => 'Cheryl Downes', 'email' => 'none@mail.com'),
			array('id' => '148', 'username' => 'arthur', 'password' => Hash::make('arthur'), 'name' => 'Arthur Benefield', 'email' => ''),
			array('id' => '149', 'username' => 'teena', 'password' => Hash::make('teena'), 'name' => 'Teena Isakson', 'email' => 'none@mail.com'),
			array('id' => '150', 'username' => 'cheryle2', 'password' => Hash::make('cheryle'), 'name' => 'Cheryle Weatherholt', 'email' => 'none@mail.com'),
			array('id' => '151', 'username' => 'clifton2', 'password' => Hash::make('clifton'), 'name' => 'Clifton Heimbach', 'email' => 'none@mail.com'),
			array('id' => '152', 'username' => 'deidre', 'password' => Hash::make('deidre'), 'name' => 'Deidre Cifaldi', 'email' => 'none@mail.com'),
			array('id' => '153', 'username' => 'hildegarde', 'password' => Hash::make('hildegarde'), 'name' => 'Hildegarde Nies', 'email' => 'none@mail.com'),
			array('id' => '154', 'username' => 'wyatt', 'password' => Hash::make('wyatt'), 'name' => 'Wyatt Mccaffrey', 'email' => 'none@mail.com'),
			array('id' => '155', 'username' => 'ileen', 'password' => Hash::make('ileen'), 'name' => 'Ileen Kress', 'email' => 'none@mail.com'),
			array('id' => '156', 'username' => 'domenic', 'password' => Hash::make('domenic'), 'name' => 'Domenic Keim', 'email' => 'none@mail.com'),
			array('id' => '157', 'username' => 'erich', 'password' => Hash::make('erich'), 'name' => 'Erich Dove', 'email' => 'none@mail.com'),
			array('id' => '158', 'username' => 'gilma', 'password' => Hash::make('gilma'), 'name' => 'Gilma Siems', 'email' => 'none@mail.com'),
			array('id' => '159', 'username' => 'alejandra', 'password' => Hash::make('alejandra'), 'name' => 'Alejandra Appleby', 'email' => ''),
			array('id' => '160', 'username' => 'kia', 'password' => Hash::make('kia'), 'name' => 'Kia Anton', 'email' => '')
		);
	}

	public static function getMeasure()
	{
		return array(
			array('id' => '197', 'measure_type_id' => '2', 'name' => 'Grams stain', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '200', 'measure_type_id' => '2', 'name' => 'SERUM AMYLASE', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '201', 'measure_type_id' => '2', 'name' => 'calcium', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '203', 'measure_type_id' => '1', 'name' => 'URIC ACID', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '210', 'measure_type_id' => '4', 'name' => 'CSF for biochemistry', 'measure_range' => '', 'unit' => ''),
			array('id' => '211', 'measure_type_id' => '4', 'name' => 'PSA', 'measure_range' => '', 'unit' => ''),
			array('id' => '212', 'measure_type_id' => '1', 'name' => 'Total', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '214', 'measure_type_id' => '1', 'name' => 'Alkaline Phosphate', 'measure_range' => '', 'unit' => 'u/l'),
			array('id' => '216', 'measure_type_id' => '2', 'name' => 'SGOT', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '218', 'measure_type_id' => '1', 'name' => 'Direct ', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '219', 'measure_type_id' => '1', 'name' => 'Total Proteins ', 'measure_range' => '', 'unit' => ''),
			array('id' => '221', 'measure_type_id' => '4', 'name' => 'LFTS', 'measure_range' => '', 'unit' => ''),
			array('id' => '222', 'measure_type_id' => '1', 'name' => 'Chloride', 'measure_range' => '', 'unit' => 'mmol/l'),
			array('id' => '223', 'measure_type_id' => '1', 'name' => 'Potassium', 'measure_range' => '', 'unit' => 'mmol/l'),
			array('id' => '224', 'measure_type_id' => '1', 'name' => 'Sodium', 'measure_range' => '', 'unit' => 'mmol/l'),
			array('id' => '225', 'measure_type_id' => '4', 'name' => 'Electrolytes', 'measure_range' => '', 'unit' => ''),
			array('id' => '226', 'measure_type_id' => '1', 'name' => 'Creatinine ', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '227', 'measure_type_id' => '1', 'name' => 'Urea', 'measure_range' => '', 'unit' => 'mg/dl'),
			array('id' => '228', 'measure_type_id' => '4', 'name' => 'RFTS', 'measure_range' => '', 'unit' => ''),
			array('id' => '229', 'measure_type_id' => '4', 'name' => 'TFT', 'measure_range' => '', 'unit' => ''),
			array('id' => '230', 'measure_type_id' => '4', 'name' => 'GXM', 'measure_range' => '', 'unit' => ''),
			array('id' => '231', 'measure_type_id' => '2', 'name' => 'Indirect COOMBS test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '232', 'measure_type_id' => '2', 'name' => 'Direct COOMBS test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '233', 'measure_type_id' => '2', 'name' => 'Du test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '234', 'measure_type_id' => '2', 'name' => 'Blood Grouping', 'measure_range' => 'O-/O+/A-/A+/B-/B+/AB-/AB+', 'unit' => ''),
			array('id' => '235', 'measure_type_id' => '2', 'name' => 'Cross Match', 'measure_range' => 'Pending/Done', 'unit' => ''),
			array('id' => '236', 'measure_type_id' => '4', 'name' => 'Epithelial cells', 'measure_range' => '', 'unit' => ''),
			array('id' => '238', 'measure_type_id' => '4', 'name' => 'ph', 'measure_range' => '', 'unit' => ''),
			array('id' => '239', 'measure_type_id' => '2', 'name' => 'Blood sugar', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '240', 'measure_type_id' => '4', 'name' => 'Spermatozoa', 'measure_range' => '', 'unit' => ''),
			array('id' => '241', 'measure_type_id' => '4', 'name' => 'Bacteria', 'measure_range' => '', 'unit' => ''),
			array('id' => '242', 'measure_type_id' => '4', 'name' => 'Red blood cells', 'measure_range' => '', 'unit' => ''),
			array('id' => '243', 'measure_type_id' => '4', 'name' => 'Yeast cells', 'measure_range' => '', 'unit' => ''),
			array('id' => '244', 'measure_type_id' => '4', 'name' => 'T. vaginalis', 'measure_range' => '', 'unit' => ''),
			array('id' => '245', 'measure_type_id' => '4', 'name' => 'S. haematobium', 'measure_range' => '', 'unit' => ''),
			array('id' => '246', 'measure_type_id' => '4', 'name' => 'Pus cells', 'measure_range' => '', 'unit' => ''),
			array('id' => '247', 'measure_type_id' => '2', 'name' => 'Urine microscopy', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '248', 'measure_type_id' => '4', 'name' => 'HCG', 'measure_range' => '', 'unit' => ''),
			array('id' => '249', 'measure_type_id' => '4', 'name' => 'Urobilinogen Phenlpyruvic acid', 'measure_range' => '', 'unit' => ''),
			array('id' => '251', 'measure_type_id' => '4', 'name' => 'Blood', 'measure_range' => '', 'unit' => ''),
			array('id' => '252', 'measure_type_id' => '4', 'name' => 'Proteins', 'measure_range' => '', 'unit' => ''),
			array('id' => '253', 'measure_type_id' => '4', 'name' => 'Ketones', 'measure_range' => '', 'unit' => ''),
			array('id' => '256', 'measure_type_id' => '1', 'name' => 'Baso#', 'measure_range' => '', 'unit' => '%'),
			array('id' => '257', 'measure_type_id' => '1', 'name' => 'Eos#', 'measure_range' => '', 'unit' => ''),
			array('id' => '258', 'measure_type_id' => '1', 'name' => 'Mon#', 'measure_range' => '', 'unit' => ''),
			array('id' => '259', 'measure_type_id' => '1', 'name' => 'Lym#', 'measure_range' => '', 'unit' => ''),
			array('id' => '260', 'measure_type_id' => '1', 'name' => 'Neu#', 'measure_range' => '', 'unit' => ''),
			array('id' => '261', 'measure_type_id' => '1', 'name' => 'WBC', 'measure_range' => '', 'unit' => 'x10Â³/ÂµL'),
			array('id' => '262', 'measure_type_id' => '1', 'name' => 'RBC', 'measure_range' => '', 'unit' => 'x10â¶/ÂµL'),
			array('id' => '263', 'measure_type_id' => '1', 'name' => 'HB', 'measure_range' => '', 'unit' => 'g/dL'),
			array('id' => '264', 'measure_type_id' => '1', 'name' => 'HCT', 'measure_range' => '', 'unit' => '%'),
			array('id' => '265', 'measure_type_id' => '1', 'name' => 'MCV', 'measure_range' => '', 'unit' => 'fL'),
			array('id' => '266', 'measure_type_id' => '1', 'name' => 'MCH', 'measure_range' => '', 'unit' => 'pg'),
			array('id' => '267', 'measure_type_id' => '1', 'name' => 'MCHC', 'measure_range' => '', 'unit' => 'g/dL'),
			array('id' => '268', 'measure_type_id' => '1', 'name' => 'RDW', 'measure_range' => '', 'unit' => '%'),
			array('id' => '269', 'measure_type_id' => '1', 'name' => 'PLATELET COUNT', 'measure_range' => '', 'unit' => 'x10Â³/ÂµL'),
			array('id' => '270', 'measure_type_id' => '1', 'name' => 'PCT', 'measure_range' => '', 'unit' => '%'),
			array('id' => '272', 'measure_type_id' => '1', 'name' => 'PDW', 'measure_range' => '', 'unit' => '%'),
			array('id' => '273', 'measure_type_id' => '4', 'name' => 'Full Haemogram', 'measure_range' => '', 'unit' => ''),
			array('id' => '274', 'measure_type_id' => '4', 'name' => 'Bleeding time test', 'measure_range' => '', 'unit' => ''),
			array('id' => '275', 'measure_type_id' => '4', 'name' => 'Clotting time test', 'measure_range' => '', 'unit' => ''),
			array('id' => '276', 'measure_type_id' => '4', 'name' => 'PTI/INR', 'measure_range' => '', 'unit' => ''),
			array('id' => '277', 'measure_type_id' => '2', 'name' => 'Sickling test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '278', 'measure_type_id' => '2', 'name' => 'ESR', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '282', 'measure_type_id' => '4', 'name' => 'Gramstain', 'measure_range' => '', 'unit' => ''),
			array('id' => '284', 'measure_type_id' => '4', 'name' => 'microscopy', 'measure_range' => '', 'unit' => ''),
			array('id' => '298', 'measure_type_id' => '4', 'name' => 'Throat swab for culture', 'measure_range' => '', 'unit' => ''),
			array('id' => '302', 'measure_type_id' => '4', 'name' => 'microscopic examination', 'measure_range' => '', 'unit' => ''),
			array('id' => '303', 'measure_type_id' => '4', 'name' => 'sperm count', 'measure_range' => '', 'unit' => ''),
			array('id' => '304', 'measure_type_id' => '2', 'name' => 'motility', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '305', 'measure_type_id' => '2', 'name' => 'viscosity', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '306', 'measure_type_id' => '4', 'name' => 'volume', 'measure_range' => '', 'unit' => ''),
			array('id' => '322', 'measure_type_id' => '4', 'name' => 'wet prep', 'measure_range' => '', 'unit' => ''),
			array('id' => '335', 'measure_type_id' => '2', 'name' => 'Indian ink', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '338', 'measure_type_id' => '1', 'name' => 'cell count', 'measure_range' => 'Number (count/ml)', 'unit' => ''),
			array('id' => '343', 'measure_type_id' => '4', 'name' => 'culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '345', 'measure_type_id' => '4', 'name' => 'CSF for microbiology', 'measure_range' => '', 'unit' => ''),
			array('id' => '346', 'measure_type_id' => '4', 'name' => 'Pus swab for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '347', 'measure_type_id' => '2', 'name' => 'KOH for fungi', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '348', 'measure_type_id' => '4', 'name' => 'semen analysis', 'measure_range' => '', 'unit' => ''),
			array('id' => '350', 'measure_type_id' => '4', 'name' => 'Aspirate for microscopy ', 'measure_range' => '', 'unit' => ''),
			array('id' => '351', 'measure_type_id' => '4', 'name' => 'HVS for microscopy ', 'measure_range' => '', 'unit' => ''),
			array('id' => '352', 'measure_type_id' => '4', 'name' => 'Synovial fluid for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '353', 'measure_type_id' => '4', 'name' => 'Synovial fluid for microscopy', 'measure_range' => '', 'unit' => ''),
			array('id' => '354', 'measure_type_id' => '4', 'name' => 'Pleural tap for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '355', 'measure_type_id' => '4', 'name' => 'Pleural tap for microscopy', 'measure_range' => '', 'unit' => ''),
			array('id' => '358', 'measure_type_id' => '4', 'name' => 'Urine Culture and Sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '359', 'measure_type_id' => '4', 'name' => 'Water Analysis', 'measure_range' => '', 'unit' => ''),
			array('id' => '361', 'measure_type_id' => '2', 'name' => 'Gram stain', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '362', 'measure_type_id' => '2', 'name' => 'Sub culture ', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '363', 'measure_type_id' => '4', 'name' => 'Blood Culture & sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '364', 'measure_type_id' => '4', 'name' => 'HVS for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '365', 'measure_type_id' => '2', 'name' => 'Sputum', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '366', 'measure_type_id' => '4', 'name' => 'Stool for C/S', 'measure_range' => '', 'unit' => ''),
			array('id' => '367', 'measure_type_id' => '4', 'name' => 'CSF', 'measure_range' => '', 'unit' => ''),
			array('id' => '368', 'measure_type_id' => '2', 'name' => 'salmonella antigen test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '369', 'measure_type_id' => '2', 'name' => 'OCCULT BLOOD', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '370', 'measure_type_id' => '4', 'name' => 'Stool for O/C', 'measure_range' => '', 'unit' => ''),
			array('id' => '371', 'measure_type_id' => '2', 'name' => 'BS for mps', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '372', 'measure_type_id' => '2', 'name' => 'Borrelia', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '373', 'measure_type_id' => '4', 'name' => 'PBF', 'measure_range' => '', 'unit' => ''),
			array('id' => '374', 'measure_type_id' => '2', 'name' => 'HEPATITIS C', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '375', 'measure_type_id' => '2', 'name' => 'HEPATITIS B', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '376', 'measure_type_id' => '2', 'name' => 'Asot Titration', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '377', 'measure_type_id' => '1', 'name' => 'Widal Titration', 'measure_range' => 'Number (count/ml)', 'unit' => ''),
			array('id' => '378', 'measure_type_id' => '2', 'name' => 'VDRL', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '379', 'measure_type_id' => '2', 'name' => 'Asot', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '380', 'measure_type_id' => '2', 'name' => 'Pregnancy test', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '381', 'measure_type_id' => '2', 'name' => 'RF', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '382', 'measure_type_id' => '2', 'name' => 'Brucella', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '383', 'measure_type_id' => '2', 'name' => 'Widal', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '384', 'measure_type_id' => '2', 'name' => 'H pylori', 'measure_range' => 'Positive/Negative', 'unit' => ''),
			array('id' => '385', 'measure_type_id' => '2', 'name' => 'CD4', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '393', 'measure_type_id' => '1', 'name' => 'HGB', 'measure_range' => '', 'unit' => 'g/dl'),
			array('id' => '403', 'measure_type_id' => '4', 'name' => 'Glucose', 'measure_range' => '', 'unit' => ''),
			array('id' => '404', 'measure_type_id' => '4', 'name' => 'Protein', 'measure_range' => '', 'unit' => ''),
			array('id' => '405', 'measure_type_id' => '4', 'name' => 'Culture', 'measure_range' => '', 'unit' => ''),
			array('id' => '406', 'measure_type_id' => '4', 'name' => 'Sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '407', 'measure_type_id' => '4', 'name' => 'ZN stain', 'measure_range' => '', 'unit' => ''),
			array('id' => '408', 'measure_type_id' => '1', 'name' => 'ALAT', 'measure_range' => '', 'unit' => 'u/l'),
			array('id' => '409', 'measure_type_id' => '1', 'name' => 'Albumin', 'measure_range' => '', 'unit' => 'g/dl'),
			array('id' => '410', 'measure_type_id' => '4', 'name' => 'sd', 'measure_range' => '', 'unit' => ''),
			array('id' => '411', 'measure_type_id' => '4', 'name' => 'Aspirate for culture and sensitivity', 'measure_range' => '', 'unit' => ''),
			array('id' => '412', 'measure_type_id' => '4', 'name' => 'Bilirubin', 'measure_range' => '', 'unit' => ''),
			array('id' => '413', 'measure_type_id' => '4', 'name' => 'Urinalysis', 'measure_range' => '', 'unit' => ''),
			array('id' => '414', 'measure_type_id' => '2', 'name' => 'ASAT', 'measure_range' => 'Low/Normal/High', 'unit' => ''),
			array('id' => '415', 'measure_type_id' => '1', 'name' => 'ASAT', 'measure_range' => '', 'unit' => 'u/l')
		);
	}

	public static function getPermission()
	{
		return array(
            array("name" => "view_names", "display_name" => "Can view patient names"),
            array("name" => "manage_patients", "display_name" => "Can add patients"),

            array("name" => "receive_external_test", "display_name" => "Can receive test requests"),
            array("name" => "request_test", "display_name" => "Can request new test"),
            array("name" => "accept_test_specimen", "display_name" => "Can accept test specimen"),
            array("name" => "reject_test_specimen", "display_name" => "Can reject test specimen"),
            array("name" => "change_test_specimen", "display_name" => "Can change test specimen"),
            array("name" => "start_test", "display_name" => "Can start tests"),
            array("name" => "enter_test_results", "display_name" => "Can enter tests results"),
            array("name" => "edit_test_results", "display_name" => "Can edit test results"),
            array("name" => "verify_test_results", "display_name" => "Can verify test results"),
            array("name" => "send_results_to_external_system", "display_name" => "Can send test results to external systems"),

            array("name" => "manage_users", "display_name" => "Can manage users"),
            array("name" => "manage_test_catalog", "display_name" => "Can manage test catalog"),
            array("name" => "manage_lab_configurations", "display_name" => "Can manage lab configurations"),
            array("name" => "view_reports", "display_name" => "Can view reports")
		);
	}

	public static function getRole()
	{
		return array(
            array("name" => "Superadmin"),
            array("name" => "Technologist"),
            array("name" => "Receptionist")
		);
	}

	public static function getReferral()
	{
		return array(
	        array("Bungoma District Hospital"),
	        array("Bumula Sub-District Hospital"),
	        array("Kenyatta National Hospital"),
	        array("Moi Referral Teaching Hospital"),
	        array("Webuye Sub-District Hospital")
		);
	}
}