<?php

class TestTypeSeed extends KBLISSeeder
{
	public static function get()
	{
		return array(
			array('id' => '117', 'name' =>  'Grams stain', 'test_category_id' => '10'),
			array('id' => '118', 'name' =>  'ZN stain', 'test_category_id' => '10'),
			array('id' => '119', 'name' =>  'urine chemistry', 'test_category_id' => '10'),
			array('id' => '120', 'name' =>  'SERUM AMYLASE', 'test_category_id' => '6'),
			array('id' => '121', 'name' =>  'calcium', 'test_category_id' => '6'),
			array('id' => '122', 'name' =>  'CALCIUM', 'test_category_id' => '6'),
			array('id' => '123', 'name' =>  'URIC ACID', 'test_category_id' => '6'),
			array('id' => '124', 'name' =>  'calcium', 'test_category_id' => '6'),
			array('id' => '125', 'name' =>  'Glucose', 'test_category_id' => '6'),
			array('id' => '126', 'name' =>  'Protein', 'test_category_id' => '6'),
			array('id' => '127', 'name' =>  'Ascitic tap for biochemistry', 'test_category_id' => '6'),
			array('id' => '128', 'name' =>  'Glucose', 'test_category_id' => '6'),
			array('id' => '129', 'name' =>  'Protein', 'test_category_id' => '6'),
			array('id' => '130', 'name' =>  'CSF for biochemistry', 'test_category_id' => '6'),
			array('id' => '131', 'name' =>  'PSA', 'test_category_id' => '6'),
			array('id' => '132', 'name' =>  'Total', 'test_category_id' => '6'),
			array('id' => '133', 'name' =>  'Albumin', 'test_category_id' => '6'),
			array('id' => '134', 'name' =>  'Alkaline Phosphate', 'test_category_id' => '6'),
			array('id' => '135', 'name' =>  'ASAT', 'test_category_id' => '6'),
			array('id' => '136', 'name' =>  'SGOT', 'test_category_id' => '6'),
			array('id' => '137', 'name' =>  'ALAT', 'test_category_id' => '6'),
			array('id' => '138', 'name' =>  'Direct ', 'test_category_id' => '6'),
			array('id' => '139', 'name' =>  'Total Proteins ', 'test_category_id' => '6'),
			array('id' => '140', 'name' =>  'Bilirubin', 'test_category_id' => '6'),
			array('id' => '141', 'name' =>  'LFTS', 'test_category_id' => '6'),
			array('id' => '142', 'name' =>  'Chloride', 'test_category_id' => '6'),
			array('id' => '143', 'name' =>  'Potassium', 'test_category_id' => '6'),
			array('id' => '144', 'name' =>  'Sodium', 'test_category_id' => '6'),
			array('id' => '145', 'name' =>  'Electrolytes', 'test_category_id' => '6'),
			array('id' => '146', 'name' =>  'Creatinine ', 'test_category_id' => '6'),
			array('id' => '147', 'name' =>  'Urea', 'test_category_id' => '6'),
			array('id' => '148', 'name' =>  'RFTS', 'test_category_id' => '6'),
			array('id' => '149', 'name' =>  'TFT', 'test_category_id' => '6'),
			array('id' => '150', 'name' =>  'GXM', 'test_category_id' => '13'),
			array('id' => '151', 'name' =>  'Indirect COOMBS test', 'test_category_id' => '13'),
			array('id' => '152', 'name' =>  'Direct COOMBS test', 'test_category_id' => '13'),
			array('id' => '153', 'name' =>  'Du test', 'test_category_id' => '13'),
			array('id' => '154', 'name' =>  'Blood Grouping', 'test_category_id' => '13'),
			array('id' => '155', 'name' =>  'Cross Match', 'test_category_id' => '13'),
			array('id' => '156', 'name' =>  'Epithelial cells', 'test_category_id' => '9'),
			array('id' => '157', 'name' =>  'Urinalysis', 'test_category_id' => '9'),
			array('id' => '158', 'name' =>  'ph', 'test_category_id' => '9'),
			array('id' => '159', 'name' =>  'Blood sugar', 'test_category_id' => '9'),
			array('id' => '160', 'name' =>  'Spermatozoa', 'test_category_id' => '9'),
			array('id' => '161', 'name' =>  'Bacteria', 'test_category_id' => '9'),
			array('id' => '162', 'name' =>  'Red blood cells', 'test_category_id' => '9'),
			array('id' => '163', 'name' =>  'Yeast cells', 'test_category_id' => '9'),
			array('id' => '164', 'name' =>  'T. vaginalis', 'test_category_id' => '9'),
			array('id' => '165', 'name' =>  'S. haematobium', 'test_category_id' => '9'),
			array('id' => '166', 'name' =>  'Pus cells', 'test_category_id' => '9'),
			array('id' => '167', 'name' =>  'Urine microscopy', 'test_category_id' => '9'),
			array('id' => '168', 'name' =>  'HCG', 'test_category_id' => '9'),
			array('id' => '169', 'name' =>  'Urobilinogen Phenlpyruvic acid', 'test_category_id' => '9'),
			array('id' => '170', 'name' =>  'Bilirubin', 'test_category_id' => '9'),
			array('id' => '171', 'name' =>  'Blood', 'test_category_id' => '9'),
			array('id' => '172', 'name' =>  'Proteins', 'test_category_id' => '9'),
			array('id' => '173', 'name' =>  'Ketones', 'test_category_id' => '9'),
			array('id' => '174', 'name' =>  'Glucose', 'test_category_id' => '9'),
			array('id' => '175', 'name' =>  'Urine chemistry', 'test_category_id' => '9'),
			array('id' => '176', 'name' =>  'Full Haemogram', 'test_category_id' => '2'),
			array('id' => '177', 'name' =>  'Eos#', 'test_category_id' => '2'),
			array('id' => '178', 'name' =>  'Mon#', 'test_category_id' => '2'),
			array('id' => '179', 'name' =>  'Lym#', 'test_category_id' => '2'),
			array('id' => '180', 'name' =>  'Neu#', 'test_category_id' => '2'),
			array('id' => '181', 'name' =>  'WBC', 'test_category_id' => '2'),
			array('id' => '182', 'name' =>  'RBC', 'test_category_id' => '2'),
			array('id' => '183', 'name' =>  'HB', 'test_category_id' => '2'),
			array('id' => '184', 'name' =>  'HCT', 'test_category_id' => '2'),
			array('id' => '185', 'name' =>  'MCV', 'test_category_id' => '2'),
			array('id' => '186', 'name' =>  'MCH', 'test_category_id' => '2'),
			array('id' => '187', 'name' =>  'MCHC', 'test_category_id' => '2'),
			array('id' => '188', 'name' =>  'RDW', 'test_category_id' => '2'),
			array('id' => '189', 'name' =>  'PLATELET COUNT', 'test_category_id' => '2'),
			array('id' => '190', 'name' =>  'PCT', 'test_category_id' => '2'),
			array('id' => '191', 'name' =>  'MPV', 'test_category_id' => '2'),
			array('id' => '192', 'name' =>  'PDW', 'test_category_id' => '2'),
			array('id' => '193', 'name' =>  'Full Haemogram', 'test_category_id' => '2'),
			array('id' => '194', 'name' =>  'Bleeding time test', 'test_category_id' => '2'),
			array('id' => '195', 'name' =>  'Clotting time test', 'test_category_id' => '2'),
			array('id' => '196', 'name' =>  'PTI/INR', 'test_category_id' => '2'),
			array('id' => '197', 'name' =>  'Sickling test', 'test_category_id' => '2'),
			array('id' => '198', 'name' =>  'ESR', 'test_category_id' => '2'),
			array('id' => '199', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '200', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '201', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '202', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '203', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '204', 'name' =>  'microscopy', 'test_category_id' => '7'),
			array('id' => '205', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '206', 'name' =>  'zn stain', 'test_category_id' => '7'),
			array('id' => '207', 'name' =>  'gramstain', 'test_category_id' => '7'),
			array('id' => '208', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '209', 'name' =>  'gramstain', 'test_category_id' => '7'),
			array('id' => '210', 'name' =>  'urine chemistry', 'test_category_id' => '7'),
			array('id' => '211', 'name' =>  'microscopy', 'test_category_id' => '7'),
			array('id' => '212', 'name' =>  'urine chemistry', 'test_category_id' => '7'),
			array('id' => '213', 'name' =>  'gramstain', 'test_category_id' => '7'),
			array('id' => '214', 'name' =>  'SENSITIVITY', 'test_category_id' => '7'),
			array('id' => '215', 'name' =>  'CULTURE', 'test_category_id' => '7'),
			array('id' => '216', 'name' =>  'gRAMSTAIN', 'test_category_id' => '7'),
			array('id' => '217', 'name' =>  'zn STAIN ', 'test_category_id' => '7'),
			array('id' => '218', 'name' =>  'Throat swab for culture', 'test_category_id' => '7'),
			array('id' => '219', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '220', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '221', 'name' =>  'microscopy', 'test_category_id' => '7'),
			array('id' => '222', 'name' =>  'microscopic examination', 'test_category_id' => '7'),
			array('id' => '223', 'name' =>  'sperm count', 'test_category_id' => '7'),
			array('id' => '224', 'name' =>  'motility', 'test_category_id' => '7'),
			array('id' => '225', 'name' =>  'viscosity', 'test_category_id' => '7'),
			array('id' => '226', 'name' =>  'volume', 'test_category_id' => '7'),
			array('id' => '227', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '228', 'name' =>  'CULTURE', 'test_category_id' => '7'),
			array('id' => '229', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '230', 'name' =>  'ZN STAIN', 'test_category_id' => '7'),
			array('id' => '231', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '232', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '233', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '234', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '235', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '236', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '237', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '238', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '239', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '240', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '241', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '242', 'name' =>  'wet prep', 'test_category_id' => '7'),
			array('id' => '243', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '244', 'name' =>  'wet prep', 'test_category_id' => '7'),
			array('id' => '245', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '246', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '247', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '248', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '249', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '250', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '251', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '252', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '253', 'name' =>  'sensitivity', 'test_category_id' => '7'),
			array('id' => '254', 'name' =>  'culture ', 'test_category_id' => '7'),
			array('id' => '255', 'name' =>  'Indian ink', 'test_category_id' => '7'),
			array('id' => '256', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '257', 'name' =>  'Gramstain', 'test_category_id' => '7'),
			array('id' => '258', 'name' =>  'cell count', 'test_category_id' => '7'),
			array('id' => '259', 'name' =>  'Indian ink', 'test_category_id' => '7'),
			array('id' => '260', 'name' =>  'cell count', 'test_category_id' => '7'),
			array('id' => '261', 'name' =>  'ZN stain', 'test_category_id' => '7'),
			array('id' => '262', 'name' =>  'Gramstain ', 'test_category_id' => '7'),
			array('id' => '263', 'name' =>  'culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '264', 'name' =>  'microscopy', 'test_category_id' => '7'),
			array('id' => '265', 'name' =>  'CSF for microbiology', 'test_category_id' => '7'),
			array('id' => '266', 'name' =>  'Pus swab for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '267', 'name' =>  'KOH for fungi', 'test_category_id' => '7'),
			array('id' => '268', 'name' =>  'semen analysis', 'test_category_id' => '7'),
			array('id' => '269', 'name' =>  'Aspirate for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '270', 'name' =>  'Aspirate for microscopy ', 'test_category_id' => '7'),
			array('id' => '271', 'name' =>  'HVS for microscopy ', 'test_category_id' => '7'),
			array('id' => '272', 'name' =>  'Synovial fluid for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '273', 'name' =>  'Synovial fluid for microscopy', 'test_category_id' => '7'),
			array('id' => '274', 'name' =>  'Pleural tap for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '275', 'name' =>  'Pleural tap for microscopy', 'test_category_id' => '7'),
			array('id' => '276', 'name' =>  'Ascitic tap for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '277', 'name' =>  'Ascitic tap for microscopy', 'test_category_id' => '7'),
			array('id' => '278', 'name' =>  'Urine Culture & Sensitivity', 'test_category_id' => '7'),
			array('id' => '279', 'name' =>  'Water Analysis', 'test_category_id' => '7'),
			array('id' => '280', 'name' =>  'Wet prep', 'test_category_id' => '7'),
			array('id' => '281', 'name' =>  'Gram stain', 'test_category_id' => '7'),
			array('id' => '282', 'name' =>  'Sub culture ', 'test_category_id' => '7'),
			array('id' => '283', 'name' =>  'Blood Culture & sensitivity', 'test_category_id' => '7'),
			array('id' => '284', 'name' =>  'HVS for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '285', 'name' =>  'Sputum', 'test_category_id' => '7'),
			array('id' => '286', 'name' =>  'Stool for C/S', 'test_category_id' => '7'),
			array('id' => '287', 'name' =>  'CSF', 'test_category_id' => '8'),
			array('id' => '288', 'name' =>  'salmonella antigen test', 'test_category_id' => '12'),
			array('id' => '289', 'name' =>  'OCCULT BLOOD', 'test_category_id' => '12'),
			array('id' => '290', 'name' =>  'Stool for O/C', 'test_category_id' => '12'),
			array('id' => '291', 'name' =>  'BS for mps', 'test_category_id' => '12'),
			array('id' => '292', 'name' =>  'Borrelia', 'test_category_id' => '12'),
			array('id' => '293', 'name' =>  'PBF', 'test_category_id' => '1'),
			array('id' => '294', 'name' =>  'HEPATITIS C', 'test_category_id' => '1'),
			array('id' => '295', 'name' =>  'HEPATITIS B', 'test_category_id' => '1'),
			array('id' => '296', 'name' =>  'Asot Titration', 'test_category_id' => '1'),
			array('id' => '297', 'name' =>  'Widal Titration', 'test_category_id' => '1'),
			array('id' => '298', 'name' =>  'VDRL', 'test_category_id' => '1'),
			array('id' => '299', 'name' =>  'Asot', 'test_category_id' => '1'),
			array('id' => '300', 'name' =>  'Pregnancy test', 'test_category_id' => '1'),
			array('id' => '301', 'name' =>  'RF', 'test_category_id' => '1'),
			array('id' => '302', 'name' =>  'Brucella', 'test_category_id' => '1'),
			array('id' => '303', 'name' =>  'Widal', 'test_category_id' => '1'),
			array('id' => '304', 'name' =>  'H pylori', 'test_category_id' => '1'),
			array('id' => '305', 'name' =>  'CD4', 'test_category_id' => '4'),
			array('id' => '306', 'name' =>  'Full Haemogram', 'test_category_id' => '6'),
			array('id' => '307', 'name' =>  'Albumin', 'test_category_id' => '1'),
			array('id' => '308', 'name' =>  'CSF for biochemistry', 'test_category_id' => '6'),
			array('id' => '309', 'name' =>  'Throat swab for culture', 'test_category_id' => '7'),
			array('id' => '310', 'name' =>  'Ascitic tap for microscopy', 'test_category_id' => '7'),
			array('id' => '311', 'name' =>  'HVS for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '312', 'name' =>  'Synovial fluid for microscopy', 'test_category_id' => '7'),
			array('id' => '313', 'name' =>  'Pleural tap for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '314', 'name' =>  'Pleural tap for microscopy', 'test_category_id' => '7'),
			array('id' => '315', 'name' =>  'Synovial fluid for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '316', 'name' =>  'Stool for C/S', 'test_category_id' => '7'),
			array('id' => '317', 'name' =>  'Aspirate for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '318', 'name' =>  'Urine Culture and Sensitivity ', 'test_category_id' => '7'),
			array('id' => '319', 'name' =>  'Pus swab for culture and sensitivity', 'test_category_id' => '7'),
			array('id' => '320', 'name' =>  'Blood Culture and sensitivity ', 'test_category_id' => '7'),
			array('id' => '321', 'name' =>  ' Aspirate for microscopy ', 'test_category_id' => '7'),
			array('id' => '322', 'name' =>  'Aspirate for microscopy', 'test_category_id' => '7'),
			array('id' => '323', 'name' =>  'culture', 'test_category_id' => '7'),
			array('id' => '324', 'name' =>  'Manual WBC Count', 'test_category_id' => '8'),
			array('id' => '325', 'name' =>  'aPTT', 'test_category_id' => '6')
		);
	}
}
